import { FieldValue } from 'firebase-admin/firestore';
import { requireAdmin } from '@/lib/staffAccess';
import { studentRef } from '@/lib/studentIdentity';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
const safeNumber = value => value === '' || value == null ? null : Number(value);
const refFor = value => studentRef(String(value || '').startsWith('elementary_') ? value : `user_${value}`);

export async function GET(request) { try { await requireAdmin(request); const ref = refFor(new URL(request.url).searchParams.get('uid')); const snapshot = await ref.collection('mockScores').orderBy('examDate', 'desc').limit(100).get(); return Response.json({ items: snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() })) }); } catch (error) { return Response.json({ error: error.message }, { status: error.status || 400 }); } }
export async function POST(request) { try { const admin = await requireAdmin(request), body = await request.json(), ref = refFor(body.uid), id = String(body.id || crypto.randomUUID()); if (!/^[A-Za-z0-9_-]{6,128}$/.test(id)) throw new Error('データIDを確認してください。'); if (!String(body.examName || '').trim() || !/^\d{4}-\d{2}-\d{2}$/.test(body.examDate || '')) throw new Error('模試名と受験日を入力してください。'); const data = { examName: String(body.examName).trim().slice(0, 100), examDate: body.examDate, provider: String(body.provider || '').trim().slice(0, 100), overallScore: safeNumber(body.overallScore), overallDeviation: safeNumber(body.overallDeviation), judgement: String(body.judgement || '').trim().slice(0, 20), subjects: Object.fromEntries(Object.entries(body.subjects || {}).slice(0, 20).map(([key, value]) => [String(key).slice(0, 30), safeNumber(value)])), memo: String(body.memo || '').trim().slice(0, 1000), updatedBy: admin.uid, updatedAt: FieldValue.serverTimestamp() }; await ref.collection('mockScores').doc(id).set(data, { merge: true }); return Response.json({ saved: true, id }); } catch (error) { return Response.json({ error: error.message }, { status: error.status || 400 }); } }
export async function DELETE(request) { try { await requireAdmin(request); const params = new URL(request.url).searchParams, ref = refFor(params.get('uid')), id = params.get('id'); if (!/^[A-Za-z0-9_-]{6,128}$/.test(id || '')) throw new Error('削除対象を確認してください。'); await ref.collection('mockScores').doc(id).delete(); return Response.json({ deleted: true }); } catch (error) { return Response.json({ error: error.message }, { status: error.status || 400 }); } }
