'use client';
import { useEffect,useMemo,useState } from 'react';
import { auth } from '@/firebaseConfig';
import './interview-settings.css';
import './interview-grid.css';

const blankPeriod={name:'保護者面談',startDate:'',endDate:'',deadline:'',active:true};
const blankTime=()=>({id:crypto.randomUUID(),startTime:'',endTime:''});
const datesBetween=(start,end)=>{if(!start||!end)return[];const rows=[];for(const cursor=new Date(`${start}T12:00:00+09:00`),last=new Date(`${end}T12:00:00+09:00`);cursor<=last;cursor.setDate(cursor.getDate()+1))rows.push(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo'}).format(cursor));return rows};

export default function InterviewSettings(){
  const[data,setData]=useState(null),[period,setPeriod]=useState(blankPeriod),[selected,setSelected]=useState(''),[timeSlots,setTimeSlots]=useState([]),[availability,setAvailability]=useState({}),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const api=async(options={})=>{const response=await fetch('/api/admin/family-services',{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${await auth.currentUser?.getIdToken()}`}}),result=await response.json();if(!response.ok)throw new Error(result.error);return result};
  const load=()=>api().then(value=>{setData(value);setSelected(current=>current||value.periods[0]?.id||'')}).catch(error=>setNotice(error.message));
  useEffect(()=>{load()},[]);
  const current=data?.periods.find(item=>item.id===selected),dates=useMemo(()=>datesBetween(current?.startDate,current?.endDate),[current?.startDate,current?.endDate]);
  useEffect(()=>{if(!current)return;const slots=(data?.slots||[]).filter(item=>item.periodId===current.id),legacyTimes=[...new Map(slots.map(item=>[`${item.startTime}_${item.endTime}`,{id:`legacy_${item.startTime.replace(':','')}_${item.endTime.replace(':','')}`,startTime:item.startTime,endTime:item.endTime}])).values()],times=current.timeSlots?.length?current.timeSlots:legacyTimes.length?legacyTimes:[blankTime()];setTimeSlots(times);const next={};for(const day of dates)for(const time of times){const row=slots.find(item=>item.date===day&&item.startTime===time.startTime&&item.endTime===time.endTime);next[`${day}_${time.id}`]=row?row.available!==false:true}setAvailability(next)},[selected,data,current?.updatedAt,dates.join(',')]);
  const save=async body=>{setBusy(true);try{const result=await api({method:'POST',body:JSON.stringify(body)});setNotice('保存しました。');await load();if(result.id)setSelected(result.id)}catch(error){setNotice(error.message)}finally{setBusy(false)}};
  const remove=async(type,id)=>{if(!confirm('削除しますか？'))return;setBusy(true);const response=await fetch(`/api/admin/family-services?type=${type}&id=${id}`,{method:'DELETE',headers:{Authorization:`Bearer ${await auth.currentUser?.getIdToken()}`}}),result=await response.json();setNotice(response.ok?'削除しました。':result.error);if(response.ok){setSelected('');await load()}setBusy(false)};
  const slotAt=(day,time)=>(data?.slots||[]).find(item=>item.periodId===selected&&item.date===day&&item.startTime===time.startTime&&item.endTime===time.endTime);
  const pending=(data?.reservations||[]).filter(item=>item.status==='pending').sort((a,b)=>`${a.date}${a.startTime}`.localeCompare(`${b.date}${b.startTime}`));
  const confirmed=(data?.reservations||[]).filter(item=>item.status==='confirmed').sort((a,b)=>`${a.date}${a.startTime}`.localeCompare(`${b.date}${b.startTime}`));
  const studentName=key=>data?.students.find(item=>item.key===key)?.name||key;
  const periodName=key=>data?.periods.find(item=>item.id===key)?.name||'保護者面談';
  return <section className="interview-settings"><header><div><small>INTERVIEW BOOKING</small><h2>保護者面談予約</h2></div><p>時間帯と日付の表を保護者画面にも表示します。申請は枠を仮押さえし、承認後にカレンダーへ反映します。</p></header>{notice&&<p role="status">{notice}</p>}
    <section className="interview-review"><h3>承認待ちの面談申請（{pending.length}件）</h3>{!pending.length?<p>承認待ちの申請はありません。</p>:pending.map(item=><article key={item.id}><div><strong>{studentName(item.studentKey)}</strong><span>{periodName(item.periodId)}／{item.date} {item.startTime}〜{item.endTime}</span></div><div><button disabled={busy} onClick={()=>save({action:'approveInterview',reservationId:item.id})}>承認して確定</button><button className="secondary" disabled={busy} onClick={()=>save({action:'rejectInterview',reservationId:item.id})}>却下して枠を再公開</button></div></article>)}</section>
    {!!confirmed.length&&<details className="interview-review"><summary>確定済みの面談（{confirmed.length}件）</summary>{confirmed.map(item=><article key={item.id}><div><strong>{studentName(item.studentKey)}</strong><span>{periodName(item.periodId)}／{item.date} {item.startTime}〜{item.endTime}</span></div><button className="secondary" disabled={busy} onClick={()=>confirm('確定済みの面談を取り消し、枠を再公開しますか？')&&save({action:'cancelConfirmedInterview',reservationId:item.id})}>確定を取り消す</button></article>)}</details>}
    <details className="interview-add-period"><summary>＋ 新しい面談期間を追加</summary><form className="interview-period-form" onSubmit={event=>{event.preventDefault();save({action:'saveInterviewPeriod',...period})}}><label>名称<input value={period.name} onChange={event=>setPeriod({...period,name:event.target.value})}/></label><label>開始日<input type="date" value={period.startDate} onChange={event=>setPeriod({...period,startDate:event.target.value})}/></label><label>終了日<input type="date" value={period.endDate} onChange={event=>setPeriod({...period,endDate:event.target.value})}/></label><label>回答期限<input type="date" value={period.deadline} onChange={event=>setPeriod({...period,deadline:event.target.value})}/></label><button disabled={busy}>面談期間を追加</button></form></details>
    <nav className="interview-period-tabs">{[...(data?.periods||[])].sort((a,b)=>a.startDate.localeCompare(b.startDate)).map(item=><button className={selected===item.id?'active':''} key={item.id} onClick={()=>setSelected(item.id)}>{item.name}<small>{item.startDate}〜{item.endDate}</small></button>)}</nav>
    {current&&<><section className="interview-times"><header><div><h3>時間帯</h3><p>固定値ではありません。必要な時間帯を追加・編集できます。</p></div><button onClick={()=>setTimeSlots(old=>[...old,blankTime()])}>＋時間帯</button></header>{timeSlots.map((item,index)=><div key={item.id}><input aria-label="開始時刻" type="time" value={item.startTime} onChange={event=>setTimeSlots(old=>old.map((row,i)=>i===index?{...row,startTime:event.target.value}:row))}/><span>〜</span><input aria-label="終了時刻" type="time" value={item.endTime} onChange={event=>setTimeSlots(old=>old.map((row,i)=>i===index?{...row,endTime:event.target.value}:row))}/><button disabled={Boolean((data?.slots||[]).some(slot=>slot.periodId===selected&&slot.startTime===item.startTime&&slot.reservationId))} onClick={()=>setTimeSlots(old=>old.filter((_,i)=>i!==index))}>削除</button></div>)}</section>
      <div className="interview-grid-wrap"><table className="interview-grid"><thead><tr><th className="interview-grid-corner">時間帯</th>{dates.map(day=><th key={day} className="interview-date-heading">{day.slice(5).replace('-',' / ')}<small>{'日月火水木金土'[new Date(`${day}T12:00:00+09:00`).getDay()]}</small></th>)}</tr></thead><tbody>{timeSlots.map(time=><tr key={time.id}><th className="interview-time-heading">{time.startTime||'--:--'}<small>〜{time.endTime||'--:--'}</small></th>{dates.map(day=>{const key=`${day}_${time.id}`,slot=slotAt(day,time),reservation=(data?.reservations||[]).find(item=>item.id===slot?.reservationId),reserved=Boolean(slot?.reservationId);return <td key={day}><button aria-label={`${day} ${time.startTime||'開始時刻未設定'}〜${time.endTime||'終了時刻未設定'}`} className={reserved?'reserved':availability[key]===false?'closed':'open'} disabled={reserved} onClick={()=>setAvailability(old=>({...old,[key]:old[key]===false}))}>{reserved?(reservation?.status==='pending'?'申請中':'確定済'):availability[key]===false?'×':'○'}</button></td>})}</tr>)}</tbody></table></div>
      <div className="interview-grid-actions"><button className="danger" disabled={busy} onClick={()=>remove('period',current.id)}>期間を削除</button><button className="primary" disabled={busy||!timeSlots.length} onClick={()=>save({action:'configureInterviewGrid',periodId:current.id,timeSlots,availability})}>時間帯と予約表を保存</button></div></>}
  </section>;
}
