'use client';
import { useEffect,useMemo,useState } from 'react';
import { auth } from '@/firebaseConfig';
import './interview-settings.css';
import './interview-grid.css';

const blankPeriod={name:'保護者面談',startDate:'',endDate:'',active:true};
const blankTime=()=>({id:crypto.randomUUID(),startTime:'',endTime:''});
const datesBetween=(start,end)=>{if(!start||!end)return[];const rows=[];for(const cursor=new Date(`${start}T12:00:00+09:00`),last=new Date(`${end}T12:00:00+09:00`);cursor<=last;cursor.setDate(cursor.getDate()+1))rows.push(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo'}).format(cursor));return rows};

export default function InterviewSettings(){
  const[data,setData]=useState(null),[period,setPeriod]=useState(blankPeriod),[selected,setSelected]=useState(''),[timeSlots,setTimeSlots]=useState([]),[availability,setAvailability]=useState({}),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const api=async(options={})=>{const response=await fetch('/api/admin/family-services',{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${await auth.currentUser?.getIdToken()}`}}),result=await response.json();if(!response.ok)throw new Error(result.error);return result};
  const load=()=>api().then(value=>{setData(value);setSelected(current=>current||value.periods[0]?.id||'')}).catch(error=>setNotice(error.message));
  useEffect(()=>{load()},[]);
  const current=data?.periods.find(item=>item.id===selected),dates=useMemo(()=>datesBetween(current?.startDate,current?.endDate),[current?.startDate,current?.endDate]);
  useEffect(()=>{if(!current)return;const slots=(data?.slots||[]).filter(item=>item.periodId===current.id),legacyTimes=[...new Map(slots.map(item=>[`${item.startTime}_${item.endTime}`,{id:`legacy_${item.startTime.replace(':','')}_${item.endTime.replace(':','')}`,startTime:item.startTime,endTime:item.endTime}])).values()],times=current.timeSlots?.length?current.timeSlots:legacyTimes.length?legacyTimes:[blankTime()];setTimeSlots(times);const next={};for(const day of dates)for(const time of times){const row=slots.find(item=>item.date===day&&item.startTime===time.startTime&&item.endTime===time.endTime);next[`${day}_${time.id}`]=row?row.available!==false:true}setAvailability(next)},[selected,data,current?.updatedAt,dates.join(',')]);
  const save=async body=>{setBusy(true);try{const result=await api({method:'POST',body:JSON.stringify(body)});setNotice('保存しました。');await load();if(result.id)setSelected(result.id)}catch(error){setNotice(error.message)}finally{setBusy(false)}};
  const remove=async(type,id)=>{if(!confirm('削除しますか？'))return;setBusy(true);const response=await fetch(`/api/admin/family-services?type=${type}&id=${id}`,{method:'DELETE',headers:{Authorization:`Bearer ${await auth.currentUser?.getIdToken()}`}}),result=await response.json();setNotice(response.ok?'削除しました。':result.error);if(response.ok){setSelected('');await load()}setBusy(false)};
  const slotAt=(day,time)=>(data?.slots||[]).find(item=>item.periodId===selected&&item.date===day&&item.startTime===time.startTime&&item.endTime===time.endTime);
  return <section className="interview-settings"><header><div><small>INTERVIEW BOOKING</small><h2>保護者面談予約</h2></div><p>日にち×時間帯の表で、予約できない枠を×にします。予約確定はDB側で排他制御されます。</p></header>{notice&&<p role="status">{notice}</p>}
    <form className="interview-period-form" onSubmit={event=>{event.preventDefault();save({action:'saveInterviewPeriod',...period})}}><label>名称<input value={period.name} onChange={event=>setPeriod({...period,name:event.target.value})}/></label><label>開始日<input type="date" value={period.startDate} onChange={event=>setPeriod({...period,startDate:event.target.value})}/></label><label>終了日<input type="date" value={period.endDate} onChange={event=>setPeriod({...period,endDate:event.target.value})}/></label><button disabled={busy}>面談期間を追加</button></form>
    <nav className="interview-period-tabs">{(data?.periods||[]).sort((a,b)=>a.startDate.localeCompare(b.startDate)).map(item=><button className={selected===item.id?'active':''} key={item.id} onClick={()=>setSelected(item.id)}>{item.name}<small>{item.startDate}〜{item.endDate}</small></button>)}</nav>
    {current&&<><section className="interview-times"><header><div><h3>時間帯</h3><p>固定値ではありません。必要な時間帯を追加・編集できます。</p></div><button onClick={()=>setTimeSlots(old=>[...old,blankTime()])}>＋時間帯</button></header>{timeSlots.map((item,index)=><div key={item.id}><input aria-label="開始時刻" type="time" value={item.startTime} onChange={event=>setTimeSlots(old=>old.map((row,i)=>i===index?{...row,startTime:event.target.value}:row))}/><span>〜</span><input aria-label="終了時刻" type="time" value={item.endTime} onChange={event=>setTimeSlots(old=>old.map((row,i)=>i===index?{...row,endTime:event.target.value}:row))}/><button disabled={Boolean((data?.slots||[]).some(slot=>slot.periodId===selected&&slot.startTime===item.startTime&&slot.reservationId))} onClick={()=>setTimeSlots(old=>old.filter((_,i)=>i!==index))}>削除</button></div>)}</section>
      <div className="interview-grid-wrap"><table className="interview-grid"><thead><tr><th>日付</th>{timeSlots.map(item=><th key={item.id}>{item.startTime||'--:--'}<small>〜{item.endTime||'--:--'}</small></th>)}</tr></thead><tbody>{dates.map(day=><tr key={day}><th>{day.slice(5).replace('-',' / ')}<small>{'日月火水木金土'[new Date(`${day}T12:00:00+09:00`).getDay()]}</small></th>{timeSlots.map(time=>{const key=`${day}_${time.id}`,slot=slotAt(day,time),reserved=Boolean(slot?.reservationId);return <td key={time.id}><button className={reserved?'reserved':availability[key]===false?'closed':'open'} disabled={reserved} onClick={()=>setAvailability(old=>({...old,[key]:old[key]===false}))}>{reserved?'予約済':availability[key]===false?'×':'○'}</button></td>})}</tr>)}</tbody></table></div>
      <div className="interview-grid-actions"><button className="danger" disabled={busy} onClick={()=>remove('period',current.id)}>期間を削除</button><button className="primary" disabled={busy||!timeSlots.length} onClick={()=>save({action:'configureInterviewGrid',periodId:current.id,timeSlots,availability})}>時間帯と予約表を保存</button></div></>}
  </section>;
}
