'use client';
import { useEffect, useState } from 'react';
import { useUnsavedChanges } from '@/lib/useUnsavedChanges';
import { auth } from '@/firebaseConfig';
const gradeLabel = value => { const grade = Number(value); if (grade >= 1 && grade <= 6) return `小${grade}`; if (grade >= 7 && grade <= 9) return `中${grade - 6}`; if (grade >= 10 && grade <= 12) return `高${grade - 9}`; return '未設定'; };
async function api(options) { const token = await auth.currentUser?.getIdToken(); const response = await fetch('/api/admin/parents', { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` } }); const result = await response.json(); if (!response.ok) throw new Error(result.error); return result; }
export default function ParentManager() {
  const edits=useUnsavedChanges('.parent-settings');
  const [data,setData]=useState(null),[selected,setSelected]=useState(''),[name,setName]=useState(''),[notice,setNotice]=useState(''),[inviteUrl,setInviteUrl]=useState(''),[inviteChildren,setInviteChildren]=useState([]);
  const load=()=>api().then(setData).catch(error=>setNotice(error.message)); useEffect(() => { load(); },[]); const parent=data?.parents.find(item=>item.uid===selected);
  const create=async()=>{try{const token=await auth.currentUser?.getIdToken();const response=await fetch('/api/admin/invites',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({role:'parent',displayName:name,childKeys:inviteChildren})});const result=await response.json();if(!response.ok)throw new Error(result.error);setInviteUrl(result.invite.url);setNotice('保護者用の招待リンクを発行しました。有効期限は7日間です。');setName('');setInviteChildren([]);}catch(error){setNotice(error.message)}};
  const toggle=key=>setData(current=>({...current,parents:current.parents.map(item=>item.uid===selected?{...item,childKeys:item.childKeys.includes(key)?item.childKeys.filter(value=>value!==key):[...item.childKeys,key]}:item)}));
  const save=async()=>{try{await api({method:'PATCH',body:JSON.stringify({uid:parent.uid,active:parent.active,childKeys:parent.childKeys})});edits.markSaved();setNotice('保護者と生徒の紐付けを保存しました。');await load();}catch(error){setNotice(error.message)}};
  return <section className="teacher-settings parent-settings"><h2>保護者アカウント・子どもの紐付け</h2><p>保護者名と子どもを選んで招待を発行します。メールアドレスとパスワードは保護者本人が登録します。</p>{notice&&<p role="status">{notice}</p>}{inviteUrl&&<div className="invite-box"><strong>招待リンク（7日間・1回限り）</strong><input readOnly value={inviteUrl}/><button onClick={()=>navigator.clipboard.writeText(inviteUrl).then(()=>setNotice('招待リンクをコピーしました。'))}>リンクをコピー</button></div>}{data&&<><div className="teacher-create invite-create"><input placeholder="保護者名" value={name} onChange={e=>setName(e.target.value)}/><button onClick={create}>保護者招待を発行</button></div><p><strong>招待に紐付ける生徒</strong></p><div className="parent-child-grid invite-children">{data.students.map(student=><label key={student.key}><input type="checkbox" checked={inviteChildren.includes(student.key)} onChange={()=>setInviteChildren(old=>old.includes(student.key)?old.filter(key=>key!==student.key):[...old,student.key])}/><span>{student.name}<small>{gradeLabel(student.grade)}</small></span></label>)}</div><label>登録済み保護者<select value={selected} onChange={e=>{setSelected(e.target.value);setInviteUrl('')}}><option value="">選択してください</option>{data.parents.map(item=><option key={item.uid} value={item.uid}>{item.displayName}{item.active===false?'（停止中）':''}</option>)}</select></label>{parent&&<div><label><input type="checkbox" checked={parent.active!==false} onChange={e=>setData(current=>({...current,parents:current.parents.map(item=>item.uid===selected?{...item,active:e.target.checked}:item)}))}/>ログインを有効にする</label><div className="parent-child-grid">{data.students.map(student=><label key={student.key}><input type="checkbox" checked={parent.childKeys.includes(student.key)} onChange={()=>toggle(student.key)}/><span>{student.name}<small>{gradeLabel(student.grade)}</small></span></label>)}</div><button onClick={save}>紐付けを保存</button></div>}</>}</section>;
}
