'use client';
import {useEffect,useState} from 'react';
import {useUnsavedChanges} from '@/lib/useUnsavedChanges';
import {auth} from '@/firebaseConfig';
async function api(options){const response=await fetch('/api/admin/parents',{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${await auth.currentUser?.getIdToken()}`}}),result=await response.json();if(!response.ok)throw new Error(result.error);return result}
export default function ParentManager(){
  const edits=useUnsavedChanges('.parent-settings');
  const[data,setData]=useState(null),[selected,setSelected]=useState(''),[name,setName]=useState(''),[notice,setNotice]=useState(''),[inviteUrl,setInviteUrl]=useState(''),[inviteChildren,setInviteChildren]=useState([]);
  const load=()=>api().then(setData).catch(error=>setNotice(error.message));useEffect(()=>{load()},[]);const parent=data?.parents.find(item=>item.uid===selected),inviteStudents=data?.inviteStudents||data?.students||[];
  const create=async()=>{try{const response=await fetch('/api/admin/invites',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await auth.currentUser?.getIdToken()}`},body:JSON.stringify({role:'parent',displayName:name,childKeys:inviteChildren})}),result=await response.json();if(!response.ok)throw new Error(result.error);setInviteUrl(result.invite.url);setNotice('保護者用の招待リンクを発行しました。有効期限は7日間です。');setName('');setInviteChildren([])}catch(error){setNotice(error.message)}};
  const changeParent=value=>setData(current=>({...current,parents:current.parents.map(item=>item.uid===selected?{...item,...value}:item)}));
  const toggle=key=>changeParent({childKeys:parent.childKeys.includes(key)?parent.childKeys.filter(value=>value!==key):[...parent.childKeys,key]});
  const save=async()=>{try{await api({method:'PATCH',body:JSON.stringify({uid:parent.uid,active:parent.active,childKeys:parent.childKeys})});edits.markSaved();setNotice('保護者情報を個別保存しました。');await load()}catch(error){setNotice(error.message)}};
  return <section className="teacher-settings parent-settings"><h2>保護者アカウント・子どもの紐付け</h2><p>未紐付けの生徒だけを選び、招待を発行します。タグは「タグ一括管理」で設定します。</p>{notice&&<p role="status">{notice}</p>}{inviteUrl&&<div className="invite-box"><strong>招待リンク（7日間・1回限り）</strong><input readOnly value={inviteUrl}/><button onClick={()=>navigator.clipboard.writeText(inviteUrl).then(()=>setNotice('招待リンクをコピーしました。'))}>リンクをコピー</button></div>}{data&&<><div className="teacher-create invite-create"><input placeholder="保護者名" value={name} onChange={e=>setName(e.target.value)}/><button disabled={!name.trim()||!inviteChildren.length} onClick={create}>保護者招待を発行</button></div><p><strong>招待に紐付ける生徒</strong></p><div className="parent-child-grid invite-children">{inviteStudents.map(student=><label key={student.key}><input type="checkbox" checked={inviteChildren.includes(student.key)} onChange={()=>setInviteChildren(old=>old.includes(student.key)?old.filter(key=>key!==student.key):[...old,student.key])}/><span>{student.name}</span></label>)}{!inviteStudents.length&&<p>未紐付けの生徒はいません。</p>}</div><label>登録済み保護者<select value={selected} onChange={e=>{setSelected(e.target.value);setInviteUrl('')}}><option value="">選択してください</option>{data.parents.map(item=><option key={item.uid} value={item.uid}>{item.displayName}{item.active===false?'（停止中）':''}</option>)}</select></label>{parent&&<div className="parent-account-editor"><label><input type="checkbox" checked={parent.active!==false} onChange={e=>changeParent({active:e.target.checked})}/>ログインを有効にする</label><div className="parent-child-grid">{data.students.map(student=><label key={student.key}><input type="checkbox" checked={parent.childKeys.includes(student.key)} onChange={()=>toggle(student.key)}/><span>{student.name}</span></label>)}</div><button onClick={save}>この保護者だけ保存</button></div>}</>}</section>
}
