import { FieldValue,Timestamp } from 'firebase-admin/firestore';
import { adminDb } from '@/lib/firebaseAdmin';
import { requireAdmin } from '@/lib/staffAccess';
export const runtime='nodejs';export const dynamic='force-dynamic';
const STATES=new Set(['applied','trial','enrolled','benefitPending','delivered']);
const json=doc=>({id:doc.id,...doc.data(),createdAt:doc.data().createdAt?.toDate?.().toISOString()||null,enrolledAt:doc.data().enrolledAt?.toDate?.().toISOString().slice(0,10)||doc.data().enrolledAt||null,benefitDueDate:doc.data().benefitDueDate?.toDate?.().toISOString().slice(0,10)||doc.data().benefitDueDate||null});
const plusTwoMonths=value=>{const date=new Date(`${value}T12:00:00+09:00`);date.setMonth(date.getMonth()+2);return Timestamp.fromDate(date)};
export async function GET(request){try{await requireAdmin(request);const snapshot=await adminDb.collection('friendReferrals').orderBy('createdAt','desc').limit(300).get();return Response.json({items:snapshot.docs.map(json)});}catch(error){return Response.json({error:error.message},{status:error.status||500})}}
export async function PATCH(request){try{const admin=await requireAdmin(request),body=await request.json(),status=STATES.has(body.status)?body.status:null;if(!status||!/^[A-Za-z0-9_-]{6,128}$/.test(body.id||''))throw new Error('更新内容を確認してください。');const enrolledAt=/^\d{4}-\d{2}-\d{2}$/.test(body.enrolledAt||'')?body.enrolledAt:null;if(['enrolled','benefitPending','delivered'].includes(status)&&!enrolledAt)throw new Error('入会日を入力してください。');await adminDb.collection('friendReferrals').doc(body.id).set({status,...(enrolledAt?{enrolledAt:Timestamp.fromDate(new Date(`${enrolledAt}T12:00:00+09:00`)),benefitDueDate:plusTwoMonths(enrolledAt)}:{}),adminNote:String(body.adminNote||'').trim().slice(0,1000),updatedBy:admin.uid,updatedAt:FieldValue.serverTimestamp(),...(status==='delivered'?{deliveredAt:FieldValue.serverTimestamp()}:{})},{merge:true});return Response.json({saved:true});}catch(error){return Response.json({error:error.message},{status:error.status||400})}}
