'use client';
import { useEffect, useState } from 'react';
import { auth } from '@/firebaseConfig';
import './student-accounts.css';

export default function StudentAccounts() {
  const [rows, setRows] = useState([]), [selected, setSelected] = useState(''), [email, setEmail] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  const api = async (options = {}) => { const response = await fetch('/api/admin/student-accounts', { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${await auth.currentUser?.getIdToken()}` } }), result = await response.json(); if (!response.ok) throw new Error(result.error); return result; };
  const load = () => api().then(result => setRows(result.students)).catch(error => setNotice(error.message));
  useEffect(() => { load(); }, []);
  const current = rows.find(item => item.studentKey === selected);
  const choose = key => { setSelected(key); setEmail(rows.find(item => item.studentKey === key)?.email || ''); setNotice(''); };
  const run = async action => { if (!current || busy) return; setBusy(true); setNotice(''); try { const result = await api({ method: 'POST', body: JSON.stringify({ action, studentKey: current.studentKey, email }) }); setNotice(action === 'promote' ? '既存の生徒IDを維持して中学生へ進級しました。' : action === 'createAccount' ? '本人アカウントを作成しました。次にログイン復旧画面で初回パスワード設定リンクを発行してください。' : '本人メールを更新しました。必要に応じてログイン復旧画面でパスワード再設定リンクを発行してください。'); await load(); if (result.authUid) setSelected(current.studentKey); } catch (error) { setNotice(error.message); } finally { setBusy(false); } };
  return <main className="student-accounts"><header><small>STUDENT IDENTITY</small><h1>本アカウント紐付け・進級</h1><p>生徒IDを変えずに本人アカウントを紐付けます。小学生の授業履歴・宿題・保護者リンクはそのまま保持します。管理者は本人パスワードを入力・閲覧しません。</p></header>{notice && <p role="status">{notice}</p>}<div className="student-account-layout"><section><h2>生徒を選択</h2><div className="student-account-list">{rows.map(item => <button key={item.studentKey} className={selected === item.studentKey ? 'active' : ''} onClick={() => choose(item.studentKey)}><strong>{item.name}</strong><span>{item.grade <= 6 ? `小${item.grade}` : `中${item.grade - 6}`}／{item.linked ? 'アカウントあり' : '未連携'}</span></button>)}</div></section><section>{current ? <><h2>{current.name}</h2><p>永続ID：{current.studentKey}</p><p>Auth UID：{current.authUid || '未発行'}</p>{current.source === 'adminStudents' && current.grade === 6 && <button disabled={busy} onClick={() => run('promote')}>中学1年へ進級</button>}{current.grade >= 7 && current.grade <= 9 && <div className="student-account-actions"><label>本人メールアドレス<input type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="student@example.com"/></label>{!current.linked && current.source === 'adminStudents' ? <button disabled={busy || !email} onClick={() => run('createAccount')}>本人アカウントを作成・紐付け</button> : current.linked ? <button disabled={busy || !email || email === current.email} onClick={() => run('updateEmail')}>本人メールを更新</button> : <p>この生徒の既存Authアカウントを確認してください。</p>}<a href="/admin/accounts?tab=recovery">パスワード設定・再設定リンク／QRを発行する ↗</a></div>}</> : <p>生徒を選択してください。</p>}</section></div></main>;
}
