'use client';
import { useEffect, useState, useRef } from 'react';
import { onAuthStateChanged, signOut } from 'firebase/auth';
import { auth } from '@/firebaseConfig';
import './parent.css';
import './workflow-improvements.css';
import './customer-portal.css';

async function parentApi(path,options={}) { const token = await auth.currentUser?.getIdToken(),config={...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(options.headers||{})}};let response;for(let attempt=0;attempt<3;attempt+=1)try{response=await fetch(path,config);break}catch(error){if(attempt===2)throw error;await new Promise(resolve=>setTimeout(resolve,500*(attempt+1)))}const result=await response.json();if(!response.ok)throw new Error(result.error);return result; }
const attendanceLabel = { present: '出席', absent: '欠席', makeup: '振替' };
const SUBJECTS = ['国語','社会','数学','理科','英語'];
const gradeLabel = value => Number(value)<=6?`小${Number(value)}`:Number(value)<=9?`中${Number(value)-6}`:Number(value)<=12?`高${Number(value)-9}`:'学年未設定';

export default function ParentPage() {
  const [data,setData]=useState(null),[student,setStudent]=useState(''),[lessons,setLessons]=useState(null),[report,setReport]=useState(null),[portal,setPortal]=useState(null),[term,setTerm]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reportVersion,setReportVersion]=useState(0),[previewTools,setPreviewTools]=useState(false);
  const [readyStudent,setReadyStudent]=useState(''),[reportBusy,setReportBusy]=useState(false),[moreBusy,setMoreBusy]=useState(false),[newsVersion,setNewsVersion]=useState(0);const currentStudent=useRef(student);currentStudent.current=student;
  useEffect(() => onAuthStateChanged(auth, async user => { if (!user) return location.href='/parent/login'; try { const value=await parentApi('/api/parent/context'); setData(value); const requested=new URLSearchParams(window.location.search).get('student');setStudent(value.children.some(item=>item.key===requested)?requested:value.children[0]?.key || ''); } catch(error) { setError(error.message); } }), []);
  useEffect(() => {
    if (!student) return undefined;
    let active = true; setError(''); setBusy(true);
    setLessons(null); setReport(null);setPortal(null);setReadyStudent('');
    Promise.allSettled([parentApi(`/api/parent/lessons?student=${encodeURIComponent(student)}`),parentApi(`/api/parent/report?student=${encodeURIComponent(student)}`),parentApi(`/api/parent/portal?student=${encodeURIComponent(student)}`)]).then(results => {
      if(!active)return;
      const [lessonResult,reportResult,portalResult]=results;
      if(lessonResult.status==='fulfilled')setLessons(lessonResult.value);
      if(portalResult.status==='fulfilled')setPortal(portalResult.value);
      if(reportResult.status==='fulfilled'){
        const meta=reportResult.value;
        const selected=term&&meta.terms.some(item=>item.id===term)?term:meta.currentTermId||meta.terms[0]?.id||'';
        setReport({...meta,summary:null,scores:[]});setTerm(selected);setReadyStudent(student);
      }
      const failures=results.map((result,index)=>result.status==='rejected'?['宿題・授業記録','学期レポート','お知らせ・カレンダー'][index]:null).filter(Boolean);
      if(failures.length)setError(`${failures.join('、')}を読み込めませんでした。ページを再読み込みしてください。`);
    }).finally(()=>{if(active)setBusy(false)});

    return () => { active = false; };
  }, [student]);
  useEffect(() => {
    if (!student || !term || readyStudent!==student) return undefined;
    let active = true; setReportBusy(true);
    setReport(previous => previous ? {...previous, summary:null, scores:[]} : previous);
    parentApi(`/api/parent/report?student=${encodeURIComponent(student)}&term=${term}`).then(value => { if (active) setReport(value); }).catch(error => { if (active) setError(error.message); }).finally(() => { if (active) setReportBusy(false); });
    return () => { active = false; };
  }, [student,readyStudent,term,reportVersion]);
  const more=async()=>{if(!lessons?.next||moreBusy)return;const key=student;setMoreBusy(true);try{const next=await parentApi(`/api/parent/lessons?student=${encodeURIComponent(key)}&after=${encodeURIComponent(lessons.next)}`);if(currentStudent.current===key)setLessons(old=>({...old,lessons:[...new Map([...old.lessons,...next.lessons].map(item=>[item.date,item])).values()],next:next.next}))}catch(error){if(currentStudent.current===key)setError(error.message)}finally{setMoreBusy(false)}};
  const child=data?.children.find(item=>item.key===student), summary=report?.summary;
  return <main className="parent-shell">
    <header><div><small>PARENT PORTAL</small><h1>保護者ページ</h1><p>{data?`${data.parent.displayName} 様`:'情報を確認しています…'}</p></div><button onClick={()=>signOut(auth).then(()=>location.href='/parent/login')}>ログアウト</button></header>
    {error&&<p className="parent-alert" role="alert">{error}</p>}
    {data&&<>{data.children.length===0?<section><p>紐付けられた生徒がいません。教室へお問い合わせください。</p></section>:<>
      {data.adminPreview?(previewTools?<aside className="parent-preview-tools"><div><strong>管理者プレビュー</strong><small>確認する生徒を選択してください</small></div><select value={student} onChange={e=>setStudent(e.target.value)}>{data.children.map(item=><option key={item.key} value={item.key}>{item.name}（{gradeLabel(item.grade)}）</option>)}</select><button onClick={()=>setPreviewTools(false)}>選択欄を隠す</button></aside>:<button className="parent-preview-restore" onClick={()=>setPreviewTools(true)}>生徒を変更</button>):<nav className="parent-child-switch">{data.children.map(item=><button key={item.key} className={student===item.key?'active':''} onClick={()=>setStudent(item.key)}>{item.name}<small>{gradeLabel(item.grade)}</small></button>)}</nav>}
      <nav className="parent-tabs" aria-label="ページ内メニュー"><a href="#homework">宿題</a><a href="#lessons">授業記録</a><a href="#report">学期レポート</a>{Number(child?.grade)>=7&&<a href="#scores">成績入力</a>}<a href="#calendar">カレンダー</a><a href="#news">お知らせ{portal&&unreadCount(filterPortal(portal,child))>0?<b>{unreadCount(filterPortal(portal,child))}</b>:''}</a></nav>
      <ParentOverview child={child} lessons={lessons} portal={portal} submission={data.submissionStatus?.[child?.key?.replace(/^(user|elementary)_/,'')]} busy={busy}/>
      <ParentRecent child={child} lessons={lessons} busy={busy}/>
      <div id="homework"><HomeworkRecords child={child} homework={lessons?.homework} busy={busy}/></div>
      <div id="lessons"><LessonRecords child={child} lessons={lessons} busy={busy||moreBusy} more={more}/></div>
      <div id="report"><TermReport child={child} report={report} term={term} setTerm={setTerm} busy={busy||reportBusy}/></div>
      {Number(child?.grade)>=7&&<div id="scores"><ParentScoreEntry key={`${student}:${term}`} child={child} report={report} term={term} setTerm={setTerm} busy={busy||reportBusy} saved={()=>setReportVersion(value=>value+1)}/></div>}
      <div className="parent-utility-grid"><div id="calendar"><ParentCalendar portal={portal}/></div><div id="news"><ParentNews portal={portal} child={child} onRead={()=>setNewsVersion(value=>value+1)}/></div></div>
    </>}</>}
  </main>;
}

const homeworkStatus = { submitted:'すべて提出', partial:'一部未完了', missed:'未提出', absent:'欠席・未確認', none:'確認済み（宿題判定なし）', laterCompleted:'後日完了' };
const readKey=()=>`parent-portal-read:${auth.currentUser?.uid||'signed-out'}`;
const unreadCount=portal=>{let read=[];if(typeof window!=='undefined')try{read=JSON.parse(localStorage.getItem(readKey())||'[]')}catch{}return [...(portal?.announcements||[]),...(portal?.documents||[])].filter(item=>!read.includes(item.id)).length};
const filterPortal=(portal,child)=>{const visible=item=>item.targetType==='all'||!item.targetType||item.targetType==='elementary'&&Number(child?.grade)<=6||item.targetType==='middle'&&Number(child?.grade)>=7&&Number(child?.grade)<=9||item.targetType==='grade'&&String(child?.grade)===String(item.targetValue)||item.targetType==='student'&&String(item.targetValue).split(',').map(value=>value.trim()).some(value=>value===child?.key||value===child?.key?.replace(/^user_/,''));return {...portal,announcements:(portal?.announcements||[]).filter(visible),documents:(portal?.documents||[]).filter(visible)}};
function ParentRecent({child,lessons,busy}) {
  const latest=lessons?.lessons?.[0];
  if (busy && !lessons) return <section className="parent-recent" aria-busy="true"><h2>最近の授業</h2><p>授業の様子を読み込み中です…</p></section>;
  if (!latest) return null;
  const reviewed=latest.reviewedHomework?.[0];
  const homework=reviewed?.review?.text || homeworkStatus[latest.homework] || '記録なし';
  const word=latest.wordTest && ['completed','makeup'].includes(latest.wordTest.status) ? `${latest.wordTest.correct} / ${latest.wordTest.total}問` : '今回は実施なし';
  return <section className="parent-recent"><div className="parent-section-heading"><div><small>RECENT LESSON</small><h2>最近の授業</h2></div><span>{latest.date.replaceAll('-',' / ')}</span></div><div className="parent-recent-grid"><div><span>出席</span><strong>{attendanceLabel[latest.attendance]||'記録なし'}</strong></div><div><span>前回の宿題</span><strong>{homework}</strong></div>{Number(child?.grade)>=7&&<div><span>単語テスト</span><strong>{word}</strong></div>}</div>{latest.comments?.[0]?.text&&<p className="parent-recent-comment">講師からの報告：{latest.comments[0].text}</p>}<a href="#lessons">授業日の詳しい記録を見る →</a></section>;
}
function ParentOverview({child,lessons,portal,submission,busy}) {
  portal=filterPortal(portal,child);const homework=lessons?.homework||[], pending=homework.filter(item=>!item.review||['pending','absent'].includes(item.review.status)), latest=lessons?.lessons?.[0], unread=portal?unreadCount(portal):0;
  const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo'}).format(new Date()), nextDate=(portal?.teachingDates||[]).find(value=>value>=today);
  const scoreMissing=Number(child?.grade)>=7&&submission&&(!submission.examReceived||!submission.internalReceived), allClear=!busy&&Boolean(lessons&&portal)&&!scoreMissing&&!pending.length&&!unread;
  return <section className="parent-overview"><div className="parent-section-heading"><div><small>HOME</small><h2>{child?.name}さんの今の状況</h2></div><span>{gradeLabel(child?.grade)}</span></div>{allClear&&<div className="parent-all-clear"><strong>確認が必要な項目はありません</strong><span>新しい連絡があると、この場所に表示されます。</span></div>}{scoreMissing&&<a className="score-bring-alert" href="#scores"><strong>提出をお願いします</strong><p>{[!submission?.examReceived&&'定期テスト',!submission?.internalReceived&&'通知表'].filter(Boolean).join('・')}が未提出です。成績は下の入力欄からも登録できます。資料の提出済み表示は、教室で受け取った後に更新されます。</p><span>確認する →</span></a>}{busy&&!lessons?<p>読み込み中…</p>:<div className="parent-overview-grid"><a href="#homework"><span>確認待ちの宿題</span><strong>{pending.length}<small>件</small></strong><em>確認する →</em></a><a href="#calendar"><span>次の営業日</span><strong className="overview-date">{nextDate?.replaceAll('-',' / ')||'未設定'}</strong><em>カレンダーを見る →</em></a><a href="#lessons"><span>最新の授業</span><strong className="overview-date">{latest?.date?.replaceAll('-',' / ')||'記録なし'}</strong><em>記録を見る →</em></a><a href="#news"><span>未読のお知らせ・資料</span><strong>{unread}<small>件</small></strong><em>確認する →</em></a></div>}</section>;
}

function ParentCalendar({portal}) {
  const dates=portal?.teachingDates||[],months=[...new Set(dates.map(date=>date.slice(0,7)))],today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo'}).format(new Date()).slice(0,7);
  const [selected,setSelected]=useState(today),month=months.includes(selected)?selected:months[0],index=months.indexOf(month);
  return <section><div className="parent-section-heading"><div><small>CLASS CALENDAR</small><h2>営業日カレンダー</h2></div><span>{portal?.year}年度</span></div>{month?<><nav className="parent-month-controls"><button disabled={index<=0} onClick={()=>setSelected(months[index-1])} aria-label="前の月">‹</button><select aria-label="表示する月" value={month} onChange={e=>setSelected(e.target.value)}>{months.map(value=><option key={value} value={value}>{value.replace('-','年 ')}月</option>)}</select><button disabled={index>=months.length-1} onClick={()=>setSelected(months[index+1])} aria-label="次の月">›</button></nav><div className="parent-calendar compact"><CalendarMonth month={month} teaching={new Set(dates)}/></div><p className="parent-calendar-key">色付きの日が授業日です。</p></>:<p>営業日はまだ公開されていません。</p>}</section>;
}
function CalendarMonth({month,teaching}) { const [year,value]=month.split('-').map(Number), first=new Date(year,value-1,1).getDay(), count=new Date(year,value,0).getDate(); return <article><h3>{value}月</h3><div className="calendar-week">{'日月火水木金土'.split('').map(day=><b key={day}>{day}</b>)}</div><div>{Array.from({length:first},(_,i)=><i key={`empty-${i}`}/>)}{Array.from({length:count},(_,index)=>{const day=index+1,id=`${year}-${String(value).padStart(2,'0')}-${String(day).padStart(2,'0')}`;return <time className={teaching.has(id)?'open':''} key={id} dateTime={id}>{day}</time>})}</div></article>; }
function ParentNews({portal,child,onRead}) { const [documentError,setDocumentError]=useState(''); portal=filterPortal(portal,child);const markRead=()=>{try{const before=JSON.parse(localStorage.getItem(readKey())||'[]');localStorage.setItem(readKey(),JSON.stringify([...new Set([...before,...(portal.announcements||[]).map(item=>item.id),...(portal.documents||[]).map(item=>item.id)])]));onRead?.()}catch{setDocumentError('既読情報を保存できませんでした。')}}; const order={important:0,request:1,normal:2},sort=items=>[...(items||[])].sort((a,b)=>(order[a.priority]??2)-(order[b.priority]??2)||b.date.localeCompare(a.date));const openDocument=async(event,item)=>{if(!item.localFile)return;event.preventDefault();const tab=window.open('','_blank');setDocumentError('');try{const token=await auth.currentUser?.getIdToken(),response=await fetch(`/api/parent/documents/${encodeURIComponent(item.id)}?student=${encodeURIComponent(child.key)}`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error('資料を開けませんでした。再度お試しください。');const url=URL.createObjectURL(await response.blob());if(tab)tab.location.href=url;else window.location.href=url;setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(error){tab?.close();setDocumentError(error.message)}};return <section><div className="parent-section-heading"><div><small>NEWS & DOCUMENTS</small><h2>教室からのお知らせ</h2></div><button type="button" onClick={markRead}>表示中を既読にする</button></div><div className="parent-news"><h3>お知らせ</h3>{!(portal?.announcements||[]).length?<p>現在のお知らせはありません。</p>:sort(portal.announcements).map(item=><article className={`priority-${item.priority}`} key={item.id}><time>{item.date}</time><strong>{item.priority==='important'?'重要｜':item.priority==='request'?'対応依頼｜':''}{item.title}</strong><p>{item.body}</p></article>)}<h3>PDF資料</h3>{documentError&&<p role="alert">{documentError}</p>}{!(portal?.documents||[]).length?<p>公開中の資料はありません。</p>:sort(portal.documents).map(item=><a className={`priority-${item.priority}`} key={item.id} href={item.localFile?'#news':item.url} onClick={event=>openDocument(event,item)} target="_blank" rel="noopener noreferrer"><span><time>{item.date}</time><strong>{item.priority==='important'?'重要｜':item.priority==='request'?'確認依頼｜':''}{item.title}</strong><small>{item.body}</small></span><b>PDFを開く ↗</b></a>)}</div></section>; }

function ParentScoreEntry({child,report,term,setTerm,busy,saved}) {
  const blankExam=()=>Object.fromEntries(SUBJECTS.map(subject=>[subject,''])), subSubjects=['音楽','美術','保体','技家'];
  const [type,setType]=useState('exam'),[testType,setTestType]=useState('中間'),[exam,setExam]=useState(blankExam),[main,setMain]=useState(()=>Object.fromEntries(SUBJECTS.map(subject=>[subject,3]))),[sub,setSub]=useState(()=>Object.fromEntries(subSubjects.map(subject=>[subject,3]))),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false);
  const selected=report?.terms?.find(item=>item.id===term), scores=report?.scores||[], examSubmitted=report?.submissionStatus?.examReceived===true, internalSubmitted=report?.submissionStatus?.internalReceived===true;
  const submit=async()=>{if(!selected||saving||busy||!report?.summary)return;setSaving(true);setNotice('');try{const payload=type==='exam'?{type,student:child.key,year:String(selected.year),term:`${selected.term}学期`,testType,exam}:{type,student:child.key,year:String(selected.year),term:`${selected.term}学期`,internalMain:main,internalSub:sub};await parentApi('/api/parent/scores',{method:'POST',body:JSON.stringify(payload)});setNotice('成績を保存しました。教室でも同じデータを確認できます。');saved()}catch(error){setNotice(error.message)}finally{setSaving(false)}};
  return <section><div className="parent-section-heading"><div><small>SCORE SUBMISSION</small><h2>{child?.name}さんの成績提出</h2></div><select value={term} onChange={e=>setTerm(e.target.value)}>{(report?.terms||[]).map(item=><option key={item.id} value={item.id}>{item.year}年度 {item.term}学期</option>)}</select></div>{!report?.summary?<p>{busy?'提出状況を確認しています…':'提出状況を取得できませんでした。ページを再読み込みしてください。'}</p>:<><div className="score-submission-status"><article className={examSubmitted?'done':'waiting'}><span>定期テスト</span><strong>{examSubmitted?'提出済み':'未提出'}</strong><small>{examSubmitted?`${scores.filter(item=>item.type==='exam').length}件登録されています`:'答案を教室へ持参してください'}</small></article><article className={internalSubmitted?'done':'waiting'}><span>通知表</span><strong>{internalSubmitted?'提出済み':'未提出'}</strong><small>{internalSubmitted?'この学期の評定を確認済みです':'通知表を教室へ持参してください'}</small></article></div><div className="parent-score-form"><nav><button className={type==='exam'?'active':''} onClick={()=>setType('exam')}>定期テストを入力</button><button className={type==='internal'?'active':''} onClick={()=>setType('internal')}>通知表を入力</button></nav>{type==='exam'?<><label>テスト名<select value={testType} onChange={e=>setTestType(e.target.value)}><option>中間</option><option>期末</option><option>実力テスト</option><option>課題テスト</option></select></label><div className="parent-score-fields">{SUBJECTS.map(subject=><label key={subject}>{subject}<input type="number" min="0" max="100" inputMode="numeric" value={exam[subject]} onChange={e=>setExam(old=>({...old,[subject]:e.target.value}))}/><small>/ 100</small></label>)}</div></>:<><p>通知表の評定（1〜5）を入力してください。</p><div className="parent-score-fields internal">{[...SUBJECTS,...subSubjects].map(subject=><label key={subject}>{subject}<select value={(SUBJECTS.includes(subject)?main:sub)[subject]} onChange={e=>(SUBJECTS.includes(subject)?setMain:setSub)(old=>({...old,[subject]:Number(e.target.value)}))}>{[1,2,3,4,5].map(value=><option key={value}>{value}</option>)}</select></label>)}</div></>} {notice&&<p className="score-entry-notice" role="status">{notice}</p>}<button className="score-entry-save" disabled={saving||busy||!selected||!report?.summary} onClick={submit}>{saving?'保存中…':'この成績を保存'}</button></div></>}</section>;
}

function HomeworkRecords({child,homework,busy}) {
  const itemLabel={submitted:'提出',partial:'途中',missed:'未提出'};
  const groups=[['attention','未提出・途中',(homework||[]).filter(item=>['partial','missed'].includes(item.review?.status)&&item.laterCompletion?.status!=='laterCompleted')],['next','次回までの宿題',(homework||[]).filter(item=>!item.review||['pending','absent'].includes(item.review.status))],['done','確認済み',(homework||[]).filter(item=>['submitted','none'].includes(item.review?.status)||item.laterCompletion?.status==='laterCompleted')]];
  const card=item=>{const results=item.review?.itemResults||{};return <article key={item.id} className={!item.review||['pending','absent'].includes(item.review.status)?'pending':''}><header><div><small>指示日 {item.assignedDate||'—'}</small><strong>確認予定 {item.dueDate||'未設定'}</strong></div><span>{homeworkStatus[item.laterCompletion?.status||item.review?.status]||'確認待ち'}</span></header><div>{(item.items||[]).map(row=><p key={row.id}><strong>{row.materialLabel}</strong><span>{row.range}</span>{results[row.id]&&<b className={`homework-item-${results[row.id]}`}>{itemLabel[results[row.id]]}</b>}</p>)}</div>{item.review?.text&&<footer>{item.laterCompletion?.text||item.review.text}</footer>}</article>};
  return <section><div className="parent-section-heading"><div><small>HOMEWORK</small><h2>{child?.name}さんの宿題</h2></div><span>状況別</span></div>{busy&&!homework?<p>読み込み中…</p>:homework&&!homework.length?<p>公開された宿題はまだありません。</p>:<div className="parent-homework-groups">{groups.filter(([, ,items])=>items.length).map(([id,title,items])=><details key={id} open={id!=='done'} className={`homework-group ${id}`}><summary>{title}<small>{items.length}件</small></summary><div className="parent-homework-list">{items.map(card)}</div></details>)}</div>}</section>;
}

function LessonRecords({child,lessons,busy,more}) { return <section><div className="parent-section-heading"><div><small>LESSON RECORDS</small><h2>{child?.name}さんの授業日の記録</h2></div><span>新しい順</span></div>{busy&&!lessons&&<p>読み込み中…</p>}{lessons&&!lessons.lessons.length&&<p>公開された授業記録はまだありません。</p>}<div className="parent-lessons">{(lessons?.lessons||[]).map(item=><article key={item.date}><header><div><time>{item.date.replaceAll('-',' / ')}</time><strong>{attendanceLabel[item.attendance]||'授業記録'}</strong></div><span>{item.termId?item.termId.replace('_','年度 第')+'学期':''}</span></header><div className="parent-statuses">{item.late&&<span>遅刻</span>}{item.forgot&&<span>忘れ物</span>}{item.wordTest&&['completed','makeup'].includes(item.wordTest.status)&&<span>単語テスト {item.wordTest.correct}/{item.wordTest.total}</span>}</div>{!item.reviewedHomework.length&&['submitted','partial','missed'].includes(item.homework)&&<div className="parent-record-block"><h3>前回の宿題状況</h3><p>{{submitted:'提出',partial:'途中',missed:'未提出'}[item.homework]}</p></div>}{item.reviewedHomework.length>0&&<div className="parent-record-block"><h3>前回の宿題状況</h3>{item.reviewedHomework.map(homework=><div key={homework.id}><p>{homework.review?.date===item.date?homework.review.text:homework.laterCompletion?.text}</p>{homework.items.map(row=><small key={row.id}>{row.materialLabel}：{row.range}{homework.review?.date===item.date&&homework.review?.itemResults?.[row.id]?` ／ ${{submitted:'提出',partial:'途中',missed:'未提出'}[homework.review.itemResults[row.id]]||''}`:''}</small>)}</div>)}</div>}{item.assignedHomework.length>0&&<div className="parent-record-block current"><h3>今回出された宿題</h3>{item.assignedHomework.map(homework=><div key={homework.id}><p>確認予定日：{homework.dueDate}</p>{homework.items.map(row=><small key={row.id}>{row.materialLabel}：{row.range}</small>)}</div>)}</div>}{item.comments.length>0&&<div className="parent-record-block comment"><h3>授業の様子</h3>{item.comments.map(comment=><p key={comment.id}>{comment.text}</p>)}</div>}</article>)}</div>{lessons?.next&&<button className="parent-more" disabled={busy} onClick={more}>{busy?'読み込み中…':'以前の授業記録を表示'}</button>}</section>; }

function TermReport({child,report,term,setTerm,busy}) { const summary=report?.summary; return <section><div className="parent-section-heading"><div><small>TERM REPORT</small><h2>{child?.name}さんの学期レポート</h2></div><select value={term} onChange={e=>setTerm(e.target.value)}>{(report?.terms||[]).map(item=><option key={item.id} value={item.id}>{item.year}年度 {item.term}学期</option>)}</select></div>{busy&&!summary?<p>集計中…</p>:summary&&<><div className="parent-summary-grid"><Summary title="宿題提出率" value={summary.homework.rate} unit="%" note={`提出 ${summary.homework.submitted}／一部 ${summary.homework.partial}／未実施 ${summary.homework.missed}`}/><Summary title="単語テスト平均" value={summary.wordTest.rate} unit="%" note={`${summary.wordTest.count}回・${summary.wordTest.correct}/${summary.wordTest.total}問`}/><Summary title="授業実施" value={summary.lessons} unit="回" note={`出席 ${summary.attendance.present}／振替 ${summary.attendance.makeup}`}/><Summary title="学習態度" value={summary.attendance.late+summary.forgot} unit="件" note={`遅刻 ${summary.attendance.late}／忘れ物 ${summary.forgot}／欠席 ${summary.attendance.absent}`}/></div><div className="parent-term-bars"><Progress label="宿題提出率" value={summary.homework.rate}/><Progress label="単語テスト平均" value={summary.wordTest.rate}/><Progress label="出席率" value={(summary.lessons+summary.attendance.absent)?Math.round(summary.lessons/(summary.lessons+summary.attendance.absent)*100):null}/></div><h3 className="parent-score-title">成績・教科別比較</h3>{!report.scores.length?<p>この学期の公開できる成績はありません。</p>:<div className="parent-scores">{report.scores.map(score=><article key={score.id}><header><strong>{score.type==='exam'?score.testType:'内申点'}</strong><span>{score.total}点</span></header><div>{score.type==='exam'?SUBJECTS.map(subject=><span key={subject}>{subject}<strong>{score.subjects[subject]??'—'}</strong><i style={{height:`${Math.min(100,Number(score.subjects[subject]||0))}%`}}/></span>):[...Object.entries(score.main),...Object.entries(score.sub)].map(([subject,value])=><span key={subject}>{subject}<strong>{value}</strong><i style={{height:`${Math.min(100,Number(value||0)/5*100)}%`}}/></span>)}</div></article>)}</div>}</>}</section>; }
function Progress({label,value}) { return <div><span>{label}</span><strong>{value??'—'}{value!==null&&'%'}</strong><i><b style={{width:`${Math.min(100,value||0)}%`}}/></i></div>; }
function Summary({title,value,unit,note}) { return <article><span>{title}</span><strong>{value??'—'}<small>{value===null?'':unit}</small></strong><p>{note}</p></article>; }
