'use client';
import { useEffect, useMemo, useState } from 'react';
import { auth } from '@/firebaseConfig';
import { useAppDialog } from '@/components/AppDialogProvider';
import './parent-services.css';

const blankUnavailable = () => ({ id: crypto.randomUUID(), date: '', startTime: '', endTime: '' });
const labels = { applied: '申込済', scheduling: '日程調整中', confirmed: '申込済', changeRequested: '変更希望を送信済み', cancelled: '取消済み' };
const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Tokyo' }).format(new Date());
const datesBetween = (start, end) => { const dates = []; if (!start || !end) return dates; for (const cursor = new Date(`${start}T12:00:00+09:00`), last = new Date(`${end}T12:00:00+09:00`); cursor <= last && dates.length < 93; cursor.setDate(cursor.getDate() + 1)) dates.push(new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Tokyo' }).format(cursor)); return dates; };

export default function ParentServices({ child }) {
  const dialog = useAppDialog();
  const [data, setData] = useState(null), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false), [choices, setChoices] = useState({}), [unavailable, setUnavailable] = useState({});
  const api = async (options = {}) => { const token = await auth.currentUser?.getIdToken(), response = await fetch(`/api/parent/services?student=${encodeURIComponent(child.key)}`, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` } }), result = await response.json(); if (!response.ok) throw new Error(result.error); return result; };
  const load = () => api().then(value => { setData(value); setUnavailable(Object.fromEntries(value.programs.map(program => [program.id, value.availability.find(item => item.programId === program.id)?.entries || [blankUnavailable()]]))); }).catch(error => setNotice(error.message));
  useEffect(() => { load(); }, [child.key]);
  const act = async (body, message) => { setBusy(true); setNotice(''); try { await api({ method: 'POST', body: JSON.stringify({ ...body, student: child.key }) }); setNotice(message); await load(); } catch (error) { setNotice(error.message); } finally { setBusy(false); } };
  const total = (program, choice) => program.application.mode === 'variable' ? Number(choice?.lessons || 0) * Number(program.application.unitPrice || 0) : Number(program.application.courses?.find(item => item.id === choice?.courseId)?.price || 0);
  const apply = async program => { const choice = choices[program.id] || {}, setting = program.application, summary = setting.mode === 'variable' ? `${choice.lessons || 0}回・${total(program, choice).toLocaleString()}円` : `${setting.courses?.find(item => item.id === choice.courseId)?.name || '未選択'}・${total(program, choice).toLocaleString()}円`; if (!await dialog.confirm({ title: '講習申込の確認', message: `${program.name}\n${summary}\nこの内容で申し込みますか？`, confirmLabel: '申し込む' })) return; act({ action: 'applyCourse', programId: program.id, ...choice }, '講習を申し込みました。'); };
  const openCoursePdf = async program => { const tab = window.open('', '_blank'); try { const response = await fetch(`/api/parent/course-document/${encodeURIComponent(program.id)}?student=${encodeURIComponent(child.key)}`, { headers: { Authorization: `Bearer ${await auth.currentUser?.getIdToken()}` } }); if (!response.ok) throw new Error('講習案内を開けませんでした。'); const url = URL.createObjectURL(await response.blob()); if (tab) tab.location.href = url; setTimeout(() => URL.revokeObjectURL(url), 60000); } catch (error) { tab?.close(); setNotice(error.message); } };
  const periods = data?.periods || [], slots = data?.slots || [], applications = data?.applications || [], sessions = data?.sessions || [];
  const grouped = useMemo(() => Object.fromEntries(periods.map(period => [period.id, slots.filter(slot => slot.periodId === period.id).sort((a, b) => `${a.date}${a.startTime}`.localeCompare(`${b.date}${b.startTime}`))])), [periods, slots]);
  const reserve = async slot => { if (!await dialog.confirm({ title: '面談申請の確認', message: `${slot.date} ${slot.startTime}〜${slot.endTime}\nこの枠を申請しますか？承認後に日時が確定します。`, confirmLabel: '申請する' })) return; await act({ action: 'reserveInterview', slotId: slot.id }, '面談を申請しました。管理者の承認をお待ちください。'); };
  const cancelPending = async slot => { if (!await dialog.confirm({ title: '面談申請の取消', message: '承認待ちの申請を取り消し、枠を再公開しますか？', confirmLabel: '申請を取り消す' })) return; await act({ action: 'cancelInterview', slotId: slot.id }, '面談申請を取り消しました。'); };
  if (!data) return <section className="parent-services"><p>{notice || '講習・面談情報を読み込んでいます…'}</p></section>;
  return <section className="parent-services"><div className="parent-section-heading"><div><small>COURSE & INTERVIEW</small><h2>講習・面談</h2></div><span>{child.name}さん</span></div>{notice && <p className="service-notice" role="status">{notice}</p>}
    {data.programs.some(program => program.application?.document) && <div className="course-document-list">{data.programs.filter(program => program.application?.document).map(program => <button key={program.id} onClick={() => openCoursePdf(program)}><strong>{program.name}</strong><span>{program.application.document.fileName}を確認 ↗</span></button>)}</div>}
    <div className="service-section"><h3>講習申込・日程</h3>{!data.programs.length ? <p>現在受付中の講習はありません。</p> : data.programs.map(program => {
      const application = applications.find(item => item.programId === program.id), mine = sessions.filter(item => item.programId === program.id), choice = choices[program.id] || {}, setting = program.application, totalLessons = Number(application?.confirmedLessons || application?.lessons || 0);
      return <article className="course-service-card" key={program.id}><header><div><strong>{program.name}</strong><small>{program.startDate}〜{program.endDate}／申込期限 {setting.deadline || '設定なし'}</small></div>{application && <b>{labels[application.status] || application.status}</b>}</header>
        {!application || application.status === 'cancelled' ? <div className="course-apply">{setting.mode === 'variable' ? <label>希望授業数<input type="number" min="1" max="100" inputMode="numeric" value={choice.lessons || ''} onChange={event => setChoices(old => ({ ...old, [program.id]: { lessons: event.target.value } }))}/><small>1回 {Number(setting.unitPrice || 0).toLocaleString()}円</small></label> : <label>コース<select value={choice.courseId || ''} onChange={event => setChoices(old => ({ ...old, [program.id]: { courseId: event.target.value } }))}><option value="">選択してください</option>{(setting.courses || []).map(item => <option key={item.id} value={item.id}>{item.name}（{item.lessons}回・{Number(item.price).toLocaleString()}円）</option>)}</select></label>}<strong>合計 {total(program, choice).toLocaleString()}円</strong><button disabled={busy || !(choice.courseId || Number(choice.lessons) > 0)} onClick={() => apply(program)}>内容を確認して申し込む</button></div> : <>
          <div className="application-summary"><span>{application.lessons}回申込</span><strong>{Number(application.total || 0).toLocaleString()}円</strong><span>{application.countConfirmedAt ? `${totalLessons}コマ中${mine.length}コマ確定／残り${Math.max(0, totalLessons - mine.length)}コマ` : '受講コマ数を調整中'}</span>{setting.deadline >= today() && <button disabled={busy} onClick={() => confirm('申込を取り消しますか？') && act({ action: 'cancelCourse', programId: program.id }, '申込を取り消しました。')}>申込を変更・取消</button>}</div>
          <details open={application.status === 'applied'}><summary>来校できない日時を登録</summary><div className="unavailable-list">{(unavailable[program.id] || []).map((row, index) => <div key={row.id || index}><input type="date" min={program.startDate} max={program.endDate} value={row.date} onChange={event => setUnavailable(old => ({ ...old, [program.id]: old[program.id].map((item, i) => i === index ? { ...item, date: event.target.value } : item) }))}/><input type="time" value={row.startTime} onChange={event => setUnavailable(old => ({ ...old, [program.id]: old[program.id].map((item, i) => i === index ? { ...item, startTime: event.target.value } : item) }))}/><input type="time" value={row.endTime} onChange={event => setUnavailable(old => ({ ...old, [program.id]: old[program.id].map((item, i) => i === index ? { ...item, endTime: event.target.value } : item) }))}/><button onClick={() => setUnavailable(old => ({ ...old, [program.id]: old[program.id].filter((_, i) => i !== index) }))}>削除</button></div>)}<button onClick={() => setUnavailable(old => ({ ...old, [program.id]: [...(old[program.id] || []), blankUnavailable()] }))}>＋日時を追加</button><button disabled={busy} onClick={() => act({ action: 'saveAvailability', programId: program.id, entries: (unavailable[program.id] || []).filter(item => item.date) }, '不可時間を保存しました。')}>不可時間を保存</button></div></details>
          {mine.length > 0 && <div className="course-schedule"><h4>確定した講習日程</h4>{mine.map(item => <p key={item.id}><time>{item.date} {item.startTime}〜{item.endTime}</time><strong>{item.subject || '講習授業'}</strong></p>)}</div>}
        </>}</article>;
    })}</div>
    <div className="service-section"><h3>保護者面談予約</h3>{!periods.length ? <p>現在受付中の面談はありません。</p> : periods.map(period => { const periodSlots = grouped[period.id] || [], dates = datesBetween(period.startDate, period.endDate), times = period.timeSlots?.length ? period.timeSlots : [...new Map(periodSlots.map(slot => [`${slot.startTime}_${slot.endTime}`, { id: `${slot.startTime}_${slot.endTime}`, startTime: slot.startTime, endTime: slot.endTime }])).values()]; const mine = periodSlots.find(slot => slot.reservedByMe && ['pending', 'confirmed'].includes(slot.reservationStatus)); const deadlinePassed = Boolean(period.deadline && period.deadline < today()); return <article className="interview-card" key={period.id}><header><strong>{period.name}</strong><small>{period.startDate}〜{period.endDate}／申請期限 {period.deadline || period.endDate}</small></header>{mine && <p className="interview-current">{mine.date} {mine.startTime}〜{mine.endTime}：{mine.reservationStatus === 'confirmed' ? '確定済み（変更・取消は教室へご連絡ください）' : '承認待ち'}</p>}{deadlinePassed && <p>申請期限を過ぎています。</p>}{!times.length ? <p>面談枠はまだ登録されていません。</p> : <div className="parent-interview-grid-wrap"><table className="parent-interview-grid"><thead><tr><th>時間帯</th>{dates.map(day => <th key={day}>{day.slice(5).replace('-', ' / ')}<small>{'日月火水木金土'[new Date(`${day}T12:00:00+09:00`).getDay()]}</small></th>)}</tr></thead><tbody>{times.map(time => <tr key={time.id}><th>{time.startTime}<small>〜{time.endTime}</small></th>{dates.map(day => { const slot = periodSlots.find(item => item.date === day && item.startTime === time.startTime && item.endTime === time.endTime), minePending = slot?.reservedByMe && slot.reservationStatus === 'pending', mineConfirmed = slot?.reservedByMe && slot.reservationStatus === 'confirmed', canApply = slot?.available && !slot?.occupied && !mine && !deadlinePassed && day >= today(); return <td key={day}>{minePending ? <button className="pending" disabled={busy} onClick={() => cancelPending(slot)}>承認待ち<small>申請取消</small></button> : mineConfirmed ? <span className="confirmed">確定済み</span> : canApply ? <button disabled={busy} onClick={() => reserve(slot)}>○<small>申請する</small></button> : <span className="unavailable">{slot?.occupied ? '受付終了' : '×'}</span>}</td>; })}</tr>)}</tbody></table></div>}</article>; })}</div>
  </section>;
}
