'use client';

import { useEffect, useMemo, useState } from 'react';
import { collection, doc, getDocs, runTransaction, updateDoc } from 'firebase/firestore';
import { onAuthStateChanged } from 'firebase/auth';
import { auth, db } from '@/firebaseConfig';
import { historyMillis, mergeRewardHistory } from '@/lib/historyCompatibility.mjs';
import '../rewardHistory/rewardHistory.css';

const gradeLabel=value=>Number(value)<=6?`小${value}`:Number(value)<=9?`中${Number(value)-6}`:`高${Number(value)-9}`;

export default function AdminRewardHistory(){
  const [students,setStudents]=useState([]),[selected,setSelected]=useState(''),[studentQuery,setStudentQuery]=useState(''),[history,setHistory]=useState([]),[filter,setFilter]=useState('unverified'),[loading,setLoading]=useState(false),[error,setError]=useState(''),[verifying,setVerifying]=useState('');
  useEffect(()=>onAuthStateChanged(auth,async user=>{if(!user){location.href='/login';return}try{const snapshot=await getDocs(collection(db,'users'));setStudents(snapshot.docs.map(item=>({id:item.id,...item.data()})).filter(item=>item.active!==false&&item.enrollmentStatus!=='withdrawn').sort((a,b)=>Number(a.grade)-Number(b.grade)||String(a.realName||a.displayName||'').localeCompare(String(b.realName||b.displayName||''),'ja')))}catch{setError('生徒一覧を取得できませんでした。')}}),[]);
  const load=async uid=>{if(!uid){setHistory([]);return}setLoading(true);setError('');try{const student=students.find(item=>item.id===uid),identity={userId:uid,userName:student?.realName||student?.displayName||'未登録'},snapshot=await getDocs(collection(db,'users',uid,'rewardHistory')),modern=snapshot.docs.map(item=>({...item.data(),...identity,historyId:item.id,legacy:false})),legacy=(Array.isArray(student?.rewardHistory)?student.rewardHistory:[]).map((item,index)=>({...item,...identity,index,legacy:true})),merged=mergeRewardHistory(modern,legacy).sort((a,b)=>historyMillis(b.date||b.createdAt)-historyMillis(a.date||a.createdAt));setHistory(merged)}catch(error){setError(`交換履歴を取得できませんでした。（${error.code||'通信エラー'}）`)}finally{setLoading(false)}};
  const choose=uid=>{setSelected(uid);setFilter('unverified');load(uid)};
  const verify=async item=>{if(!window.confirm(`${item.userName}さんの「${item.name}」を引き渡し済みにしますか？`))return;setVerifying(item.historyId||String(item.index));try{if(!item.legacy&&item.historyId){await updateDoc(doc(db,'users',item.userId,'rewardHistory',item.historyId),{verified:true,verifiedAt:new Date()})}else{const ref=doc(db,'users',item.userId);await runTransaction(db,async transaction=>{const snapshot=await transaction.get(ref),list=snapshot.data()?.rewardHistory,original=list?.[item.index];if(!original||original.name!==item.name||Number(original.cost)!==Number(item.cost)||historyMillis(original.date)!==historyMillis(item.date))throw new Error('履歴が変更されています。再読み込みしてください。');const next=[...list];next[item.index]={...original,verified:true,verifiedAt:new Date()};transaction.update(ref,{rewardHistory:next})})}await load(selected)}catch(error){setError(error.message||'確認状態を保存できませんでした。')}finally{setVerifying('')}};
  const visible=useMemo(()=>filter==='unverified'?history.filter(item=>!item.verified):history,[history,filter]);
  const matchingStudents=students.filter(item=>item.id===selected||`${item.realName||item.displayName||''} ${gradeLabel(item.grade)}`.toLocaleLowerCase('ja').includes(studentQuery.trim().toLocaleLowerCase('ja')));
  return <div className="admin-history-container"><h1 className="admin-history-title">景品の引き渡し</h1><p className="history-range-note">生徒を探して未確認の交換を表示し、引き渡したら確認します。</p>
    <div className="admin-student-search"><label>名前・学年で絞り込み<input type="search" value={studentQuery} onChange={event=>setStudentQuery(event.target.value)} placeholder="例：山田、中2" /></label><label className="history-student-select">生徒<select value={selected} onChange={event=>choose(event.target.value)}><option value="">生徒を選択してください</option>{matchingStudents.map(item=><option key={item.id} value={item.id}>{item.realName||item.displayName||'名前未設定'}（{gradeLabel(item.grade)}）</option>)}</select></label></div>
    {selected&&<div className="filter-buttons"><button className={`filter-button ${filter==='all'?'active':''}`} onClick={()=>setFilter('all')}>全件</button><button className={`filter-button ${filter==='unverified'?'active':''}`} onClick={()=>setFilter('unverified')}>未確認のみ</button><button onClick={()=>load(selected)}>再読み込み</button></div>}
    {error&&<p role="alert">{error}</p>}{loading?<p className="loading-text">読み込み中...</p>:!selected?<p className="no-history">確認する生徒を選択してください。</p>:!visible.length?<p className="no-history">該当する履歴はありません。</p>:<table className="admin-history-table"><thead><tr><th>生徒名</th><th>景品名</th><th>ポイント</th><th>交換日</th><th>確認状態</th><th>操作</th></tr></thead><tbody>{visible.map(item=><tr key={`${item.legacy?'legacy':item.historyId}-${item.index??''}`}><td>{item.userName}</td><td>{item.name}</td><td>{item.cost} pt</td><td>{item.date||item.createdAt?new Date(historyMillis(item.date||item.createdAt)).toLocaleString('ja-JP'):'不明'}</td><td>{item.verified?'引き渡し済み':'未確認'}</td><td>{!item.verified&&<button className="verify-button" disabled={Boolean(verifying)} onClick={()=>verify(item)}>{verifying===(item.historyId||String(item.index))?'確認中…':'引き渡し済みにする'}</button>}</td></tr>)}</tbody></table>}
  </div>;
}
