import { FieldValue } from 'firebase-admin/firestore';
import { adminDb } from '@/lib/firebaseAdmin';
import { requireAdmin } from '@/lib/staffAccess';
export const dynamic='force-dynamic';
const clean=(value,max=200)=>String(value||'').trim().slice(0,max);
function validate(item){const value={name:clean(item.name,120),type:['lesson','course','school','classroom','interview','exam','other'].includes(item.type)?item.type:'other',startDate:clean(item.startDate,10),endDate:clean(item.endDate,10)||clean(item.startDate,10),startTime:clean(item.startTime,5),endTime:clean(item.endTime,5),targetType:['all','grade','school','student','parentTag'].includes(item.targetType)?item.targetType:'all',targetValue:clean(item.targetValue,300),showParent:item.showParent!==false,showStudent:item.showStudent===true};if(!value.name||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(value.startDate)||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(value.endDate)||value.endDate<value.startDate)throw new Error('イベント名と期間を確認してください。');return value}
export async function GET(request){try{await requireAdmin(request);const snapshot=await adminDb.collection('parentEvents').orderBy('startDate','desc').limit(300).get();return Response.json({items:snapshot.docs.map(doc=>({id:doc.id,...doc.data()}))})}catch(error){return Response.json({error:error.message},{status:error.status||400})}}
export async function POST(request){try{const admin=await requireAdmin(request),body=await request.json(),id=/^[A-Za-z0-9_-]{1,128}$/.test(body.id||'')?body.id:crypto.randomUUID(),ref=adminDb.collection('parentEvents').doc(id),old=await ref.get(),now=FieldValue.serverTimestamp();await ref.set({...validate(body),createdAt:old.data()?.createdAt||now,createdBy:old.data()?.createdBy||admin.uid,updatedAt:now,updatedBy:admin.uid},{merge:true});return Response.json({saved:true,id})}catch(error){return Response.json({error:error.message},{status:error.status||400})}}
export async function DELETE(request){try{await requireAdmin(request);const id=new URL(request.url).searchParams.get('id');if(!/^[A-Za-z0-9_-]{1,128}$/.test(id||''))throw new Error('イベントを選択してください。');await adminDb.collection('parentEvents').doc(id).delete();return Response.json({deleted:true})}catch(error){return Response.json({error:error.message},{status:error.status||400})}}
