'use client';
import { useEffect, useMemo, useState } from 'react';
import { onAuthStateChanged, signOut } from 'firebase/auth';
import { auth } from '@/firebaseConfig';
import { japanDateId } from '@/lib/academicCalendar.mjs';
import { aggregateItemResults, ITEM_RESULT_LABELS, reviewableHomeworkItems, validateAssignment } from '@/lib/homeworkModel.mjs';
import './teacher.css';
import './workflow-improvements.css';
import './mobile-workflow.css';

const getWeek = value => { const date = new Date(`${value}T12:00:00Z`); const start = new Date(Date.UTC(date.getUTCFullYear(), 0, 1)); return Math.ceil((((date - start) / 86400000) + start.getUTCDay() + 1) / 7); };
const gradeLabel = value => Number(value)<=6?`小${Number(value)}`:Number(value)<=9?`中${Number(value)-6}`:Number(value)<=12?`高${Number(value)-9}`:'学年未設定';
const WEEKDAYS = ['日','月','火','水','木','金','土'];
async function api(url, options) { const token = await auth.currentUser?.getIdToken(),config={ ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}`, ...(options?.headers || {}) } };let response;for(let attempt=0;attempt<3;attempt+=1)try{response=await fetch(url,config);break}catch(error){if(attempt===2)throw error;await new Promise(resolve=>setTimeout(resolve,500*(attempt+1)))}const result = await response.json(); if (!response.ok) throw new Error(result.error); return result; }

export default function TeacherPage() {
  const [date, setDate] = useState(japanDateId()), [context, setContext] = useState(null), [studentKey, setStudentKey] = useState(''), [homeworkData, setHomeworkData] = useState(null);
  const [gradeFilter,setGradeFilter]=useState('all'),[studentQuery,setStudentQuery]=useState(''),[scheduledOnly,setScheduledOnly]=useState(true);
  const [reviewId, setReviewId] = useState(''), [itemResults, setItemResults] = useState({}), [commentIds, setCommentIds] = useState([]), [late, setLate] = useState(false), [forgot, setForgot] = useState(false), [note, setNote] = useState('');
  const [wordCorrect,setWordCorrect]=useState(''),[wordTotal,setWordTotal]=useState('');
  const [attendance,setAttendance]=useState('present'),[originalDate,setOriginalDate]=useState('');
  const [nextItems, setNextItems] = useState([{ materialId: '', range: '' }]), [dueDate, setDueDate] = useState(''), [notice, setNotice] = useState(''), [saving, setSaving] = useState(false);
  const [draftLoadedKey,setDraftLoadedKey]=useState('');
  const [homework,setHomework]=useState('none'),[assignmentId,setAssignmentId]=useState(''),[assignmentVersion,setAssignmentVersion]=useState(null),[reload,setReload]=useState(0),[dirty,setDirty]=useState(false);
  const student = context?.students.find(item => item.key === studentKey);
  const filteredStudents=useMemo(()=>(context?.students||[]).filter(item=>(!scheduledOnly||item.scheduled)&&(gradeFilter==='all'||String(item.grade)===gradeFilter)&&(!studentQuery||item.name.includes(studentQuery.trim()))),[context,scheduledOnly,gradeFilter,studentQuery]);
  useEffect(()=>{if(studentKey&&!filteredStudents.some(item=>item.key===studentKey))setStudentKey('')},[filteredStudents,studentKey]);
  useEffect(() => {let active=true;setContext(null);setStudentKey('');const unsubscribe=onAuthStateChanged(auth,user=>{if(!user)location.href='/teacher/login';else api(`/api/teacher/context?date=${date}`).then(value=>{if(active)setContext(value)}).catch(error=>{if(active)setNotice(error.message)})});return()=>{active=false;unsubscribe()}}, [date]);
  useEffect(()=>{
    let active=true;setDraftLoadedKey('');setHomeworkData(null);setNotice('');setDirty(false);
    if(!studentKey)return;
    const key=`teacher-draft:${auth.currentUser?.uid}:${date}:${studentKey}`;
    const apply=value=>{setReviewId(value.reviewId??value.homeworkReview?.assignmentId??'');setItemResults(value.itemResults??value.homeworkReview?.itemResults??{});setCommentIds(value.commentIds||[]);setLate(value.late===true);setForgot(value.forgot===true);setNote(value.note??value.behaviorNote??'');setWordCorrect(value.wordCorrect??value.wordTest?.correct??'');setWordTotal(value.wordTotal??value.wordTest?.total??student?.wordTestQuestionCount??20);setAttendance(value.attendance??value.status??'present');setOriginalDate(value.originalDate||value.originalLessonDate||'');setNextItems(value.nextItems||[{materialId:'',range:''}]);setDueDate(value.dueDate||'');setHomework(value.homework||'none');setAssignmentId(value.nextId||crypto.randomUUID());setAssignmentVersion(value.nextVersion??null)};
    apply({});
    Promise.all([api(`/api/teacher/context?date=${date}&student=${encodeURIComponent(studentKey)}`),api(`/api/admin/homework?student=${encodeURIComponent(studentKey)}&date=${date}`)]).then(async([value,homeworkValue])=>{
      const reviewId=value.existingRecord?.homeworkReview?.assignmentId;
      if(reviewId&&!homeworkValue.items.some(item=>item.id===reviewId)){const selected=await api(`/api/admin/homework?student=${encodeURIComponent(studentKey)}&date=${date}&assignment=${encodeURIComponent(reviewId)}`);homeworkValue.items.push(...selected.items)}
      if(!active)return;
      const assigned=homeworkValue.items.find(item=>item.assignedDate===date);
      const record={...value.existingRecord,...(assigned?{nextId:assigned.id,nextVersion:assigned.version,nextItems:assigned.items.map(item=>({materialId:item.materialId,range:item.range})),dueDate:assigned.dueDate}:{})};
      let local;try{local=JSON.parse(localStorage.getItem(key)||'null')}catch{}
      apply(local||record);setDirty(Boolean(local));setHomeworkData(homeworkValue);setDraftLoadedKey(key);setNotice(local?'保存前の入力を復元しました。':value.existingRecord?'入力済みの記録です。訂正して保存できます。':'');
    }).catch(error=>{if(active)setNotice(error.message)});
    return()=>{active=false};
  },[date,studentKey,reload]);
  useEffect(()=>{if(!dirty||!studentKey||draftLoadedKey!==`teacher-draft:${auth.currentUser?.uid}:${date}:${studentKey}`)return;try{localStorage.setItem(draftLoadedKey,JSON.stringify({reviewId,itemResults,commentIds,late,forgot,note,wordCorrect,wordTotal,attendance,originalDate,nextItems,dueDate,homework,nextId:assignmentId,nextVersion:assignmentVersion}))}catch{}},[studentKey,date,draftLoadedKey,reviewId,itemResults,commentIds,late,forgot,note,wordCorrect,wordTotal,originalDate,dueDate,nextItems,homework,assignmentId,assignmentVersion,attendance,dirty]);
  useEffect(()=>{const warn=event=>{if(dirty){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
  const pending = useMemo(() => (homeworkData?.items || []).filter(item => item.assignedDate<=date&&(!item.review || ['pending','absent'].includes(item.review.status)||item.review.date===date||item.id===reviewId)), [homeworkData,date,reviewId]);
  const reviewAssignment = pending.find(item=>item.id===reviewId);
  const isMiddle=student?.grade>=7&&student?.grade<=9,isElementary=student?.grade>=1&&student?.grade<=6;
  const materials=(homeworkData?.templates?.materials||[]).filter(item=>!item.audience||item.audience==='all'||item.audience===(isElementary?'elementary':'middle'));
  const save = async () => {
    if (!student || saving || !draftLoadedKey || !homeworkData) return; setSaving(true); setNotice('');let lessonSaved=false;
    try {
      const termId = context.term.id, weekId = `${context.term.year}-W${String(getWeek(date)).padStart(2,'0')}`;
      const reviewStatus = reviewAssignment ? aggregateItemResults(reviewAssignment.items,itemResults) : 'pending';
      if (attendance!=='absent'&&reviewAssignment && reviewStatus === 'pending') throw new Error('各宿題を「提出・途中・未提出」から選択してください。');
      const validItems=student.grade>=10?[]:nextItems.filter(item=>item.materialId||item.range.trim());
      const oldAssignment=homeworkData.items.find(item=>item.id===assignmentId);
      const unchanged=oldAssignment&&oldAssignment.dueDate===dueDate&&JSON.stringify(oldAssignment.items.map(item=>[item.materialId,item.range]))===JSON.stringify(validItems.map(item=>[item.materialId,item.range]));
      if(validItems.length&&!unchanged)validateAssignment({assignedDate:date,dueDate,items:validItems},homeworkData.templates);
      if(oldAssignment&&!validItems.length)throw new Error('登録済み宿題は空欄で削除できません。管理者に確認してください。');
      if(oldAssignment?.review&&!['pending','absent'].includes(oldAssignment.review.status)&&!unchanged)throw new Error('確認済みの宿題内容は変更できません。');
      const homeworkReview = reviewId ? { assignmentId: reviewId, status: reviewStatus, itemResults } : null;
      if(isMiddle&&attendance!=='absent'&&wordCorrect!==''&&(!Number.isInteger(Number(wordCorrect))||Number(wordCorrect)<0||!Number.isInteger(Number(wordTotal))||Number(wordTotal)<1||Number(wordCorrect)>Number(wordTotal)))throw new Error('単語テストの正答数と問題数を確認してください。');
      const learningRecord = { homework: attendance==='absent'?'notEvaluated':reviewId ? (reviewStatus === 'submitted' ? 'submitted' : reviewStatus) : homework, wordTest: isMiddle ? (attendance==='absent'?{status:'pending'}:wordCorrect!==''?{status:'completed',correct:wordCorrect,total:wordTotal}:{status:'notScheduled'}) : { status: 'notScheduled', correct: null, total: null }, late:isMiddle&&attendance!=='absent'&&late, forgot:isMiddle&&attendance!=='absent'&&forgot, behaviorNote: note };
      if(attendance==='makeup'&&!originalDate)throw new Error('振替元の授業日を入力してください。');
      if (student.grade >= 7 && student.grade <= 9) await api('/api/admin/lesson-records', { method: 'POST', body: JSON.stringify({ uid: student.id, date, termId, weekId, homeworkReview, commentIds, record: { ...learningRecord, attendance,originalLessonDate:originalDate } }) });
      else await api('/api/admin/lesson-attendance', { method: 'POST', body: JSON.stringify({ action: 'save', student: { id: student.id, source: student.source, grade: student.grade }, date, status:attendance,originalDate,...(isElementary?{note, learningRecord, homeworkReview, commentIds}:{}) }) });
      lessonSaved=true;
      if (validItems.length&&!unchanged) {
        if (!dueDate) throw new Error('新しい宿題の確認予定日を入力してください。');
        await api('/api/admin/homework', { method: 'POST', body: JSON.stringify({ id: assignmentId, version:assignmentVersion, student: student.key, assignedDate: date, dueDate, items: validItems }) });
      }
      try{localStorage.removeItem(draftLoadedKey)}catch{}setDraftLoadedKey('');setDirty(false);setNotice('授業記録を保存しました。');setContext(old=>({...old,inputStatus:{...(old.inputStatus||{}),[student.key]:{updatedAt:new Date().toISOString(),updatedBy:auth.currentUser?.uid||null}}}));setReload(value=>value+1);
    } catch (error) { setNotice(`${lessonSaved?'授業記録は保存済みですが、新しい宿題を保存できませんでした。 ':''}${error.message}`); } finally { setSaving(false); }
  };
  const scheduled=(context?.students||[]).filter(item=>item.scheduled),completed=scheduled.filter(item=>context?.inputStatus?.[item.key]).length;
  return <main className="teacher-shell"><header><div><small>TEACHER CONSOLE</small><h1>授業後の入力</h1><p>{context?.displayName || ''}　その日に担当した生徒を選択してください。</p></div><button onClick={() => signOut(auth).then(() => location.href='/teacher/login')}>ログアウト</button></header>
    <fieldset className="teacher-edit-fields" disabled={saving} onChange={event=>{if(!event.target.closest('.teacher-flow'))setDirty(true)}} onClick={event=>{if(event.target.closest('button')&&!event.target.closest('.teacher-flow,.teacher-save'))setDirty(true)}}>{context&&<div className="teacher-daily-status"><span><strong>{scheduled.length}</strong>予定</span><span className="done"><strong>{completed}</strong>入力済み</span><span className="pending"><strong>{Math.max(0,scheduled.length-completed)}</strong>未入力</span></div>}
    {notice && <p className="teacher-notice" role="status">{notice}</p>}<section className="teacher-flow"><label><span>1. 授業日</span><input type="date" value={date} onChange={e => setDate(e.target.value)} /><small>{context?`${WEEKDAYS[context.weekday]}曜日の通塾予定を表示中`:''}</small></label><div className="teacher-student-picker"><span>2. 担当生徒</span><div className="teacher-filters"><label><input type="checkbox" checked={scheduledOnly} onChange={e=>setScheduledOnly(e.target.checked)}/>予定生徒のみ</label><select aria-label="学年で絞り込み" value={gradeFilter} onChange={e=>setGradeFilter(e.target.value)}><option value="all">全学年</option>{[1,2,3,4,5,6,7,8,9,10,11,12].map(value=><option key={value} value={value}>{gradeLabel(value)}</option>)}</select><input aria-label="名前で検索" placeholder="名前で検索" value={studentQuery} onChange={e=>setStudentQuery(e.target.value)}/></div><div className="teacher-quick-students" role="group" aria-label="担当生徒を選択">{filteredStudents.map(item=><button type="button" key={item.key} className={studentKey===item.key?'selected':''} aria-pressed={studentKey===item.key} onClick={()=>setStudentKey(item.key)}><strong>{item.name}</strong><small>{gradeLabel(item.grade)} · {context?.inputStatus?.[item.key]?'入力済み':'未入力'}</small></button>)}</div>{!filteredStudents.length&&<p className="teacher-empty-students">該当する生徒はいません。絞り込みを変更してください。</p>}{scheduledOnly&&<small>振替など予定外の生徒は「予定生徒のみ」を外すと選べます。</small>}</div></section>{student&&homeworkData&&<section><h2>出席状況</h2><div className="teacher-attendance">{[['present','出席'],['absent','欠席'],['makeup','振替出席']].map(([value,label])=><button type="button" key={value} className={attendance===value?'selected':''} onClick={()=>setAttendance(value)}>{label}</button>)}</div>{attendance==='makeup'&&<label>振替元の授業日<input type="date" value={originalDate} onChange={e=>setOriginalDate(e.target.value)}/></label>}</section>}
    {student&&homeworkData&&<div className="teacher-selected-student"><strong>{student.realName||student.name}</strong><small>{gradeLabel(student.grade)} · {date}</small></div>}{student && homeworkData && student.grade<10 && <><section><h2>今回の確認</h2>{pending.length ? <><label>確認する宿題<select value={reviewId} onChange={e => {setReviewId(e.target.value);const selected=pending.find(item=>item.id===e.target.value);setItemResults(selected?.review?.date===date?selected.review.itemResults||{}:{})}}><option value="">今回は確認しない</option>{pending.map(item => <option key={item.id} value={item.id}>{item.dueDate}予定：{item.items.map(row => `${row.materialLabel} ${row.range}`).join('／')}</option>)}</select></label>{attendance!=='absent'&&reviewAssignment&&reviewableHomeworkItems(reviewAssignment.items).map(item=><div key={item.id}><strong>{item.materialLabel} {item.range}</strong><div className="teacher-checks">{Object.entries(ITEM_RESULT_LABELS).map(([status,label])=><label key={status}><input type="radio" name={`homework-${item.id}`} checked={itemResults[item.id]===status} onChange={()=>setItemResults(old=>({...old,[item.id]:status}))}/>{label}</label>)}</div></div>)}</> : <p>確認待ちの宿題はありません。</p>}
      {!reviewId&&attendance!=='absent'&&<div className="teacher-attendance manual-homework">{[['none','宿題なし'],...Object.entries(ITEM_RESULT_LABELS)].map(([value,label])=><button type="button" key={value} className={homework===value?'selected':''} onClick={()=>setHomework(value)}>{label}</button>)}</div>}{attendance==='absent'&&<p>欠席のため宿題の判定は保留にします。</p>}
      {isMiddle&&<div className="teacher-word"><h3>単語テスト</h3><label>正答数<input type="number" min="0" inputMode="numeric" value={wordCorrect} onChange={e=>setWordCorrect(e.target.value)}/></label><span>/</span><label>問題数<input type="number" min="1" inputMode="numeric" value={wordTotal} onChange={e=>setWordTotal(e.target.value)}/></label></div>}{isMiddle&&<div className="teacher-checks"><label><input type="checkbox" checked={late} onChange={e => setLate(e.target.checked)} />遅刻</label><label><input type="checkbox" checked={forgot} onChange={e => setForgot(e.target.checked)} />忘れ物</label></div>}<p>保護者向け定型コメント</p><div className="teacher-comment-selects">{['positive','negative'].map(tone=>{const options=homeworkData.templates.comments.filter(item=>(item.tone||'positive')===tone),selected=options.find(item=>commentIds.includes(item.id))?.id||'';return <label key={tone}>{tone==='positive'?'プラスのコメント':'改善のコメント'}<select value={selected} onChange={e=>setCommentIds(old=>[...old.filter(id=>!options.some(item=>item.id===id)),...(e.target.value?[e.target.value]:[])])}><option value="">選択しない</option>{options.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label>})}</div><label className="teacher-private-note">教室内メモ<small>管理者・講師だけが確認します</small><textarea value={note} onChange={e => setNote(e.target.value)} placeholder="保護者には表示されません" /></label></section>
      <section><h2>今回出した宿題</h2><p className="teacher-help">教材・範囲と確認予定日を入力します。保存済みの宿題は読み込んだ内容を訂正できます。</p>{nextItems.map((item,index) => <div className="teacher-homework" key={index}><select value={item.materialId} onChange={e => setNextItems(old => old.map((row,i) => i===index ? {...row,materialId:e.target.value,range:''}:row))}><option value="">教材を選択</option>{materials.map(material => <option key={material.id} value={material.id}>{material.label}</option>)}</select><TeacherRange material={materials.find(material=>material.id===item.materialId)} value={item.range} onChange={range=>setNextItems(old=>old.map((row,i)=>i===index?{...row,range}:row))}/><button type="button" aria-label={`宿題${index+1}を削除`} onClick={()=>setNextItems(old=>old.filter((_,i)=>i!==index))}>削除</button></div>)}<button onClick={() => setNextItems(old => [...old,{materialId:'',range:''}])}>＋ 宿題を追加</button><label>確認予定日<input type="date" min={date} value={dueDate} onChange={e => setDueDate(e.target.value)} /></label></section></>}{student&&<button className="teacher-save" disabled={saving||!homeworkData||draftLoadedKey!==`teacher-draft:${auth.currentUser?.uid}:${date}:${studentKey}`} onClick={save}>{saving?'保存中…':'この授業記録を保存'}</button>}
    {student&&!homeworkData&&<p role="status">記録を読み込み中です。{notice&&<button onClick={()=>setReload(value=>value+1)}>再読み込み</button>}</p>}</fieldset>
  </main>;
}
function TeacherRange({material,value,onChange}){if(material?.rangeType!=='number')return <input placeholder="ページ・範囲" value={value} onChange={e=>onChange(e.target.value)}/>;const numbers=String(value||'').match(/\d+/g)||[];return <span className="number-range"><input type="number" min="1" placeholder="開始番号" value={numbers[0]||''} onChange={e=>onChange(`No.${e.target.value}〜${numbers[1]||''}`)}/><b>〜</b><input type="number" min="1" placeholder="終了番号" value={numbers[1]||''} onChange={e=>onChange(`No.${numbers[0]||''}〜${e.target.value}`)}/></span>}
