'use client';
import { useEffect, useState } from 'react';
import { auth } from '@/firebaseConfig';
import { onAuthStateChanged } from 'firebase/auth';
import { shiftDateAt, shiftWeekStart } from '@/lib/weeklyShifts';
import './shift-preferences.css';

const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Tokyo' }).format(new Date());
const subjects = [['japanese', '国語'], ['math', '数学'], ['english', '英語'], ['science', '理科'], ['social', '社会'], ['other', 'その他']];
const weekdayNames = ['月', '火', '水', '木', '金', '土'];

export default function ShiftPreferences() {
  const [week, setWeek] = useState(shiftWeekStart(today())), [periods, setPeriods] = useState([]), [subjectsSelected, setSubjectsSelected] = useState([]), [grades, setGrades] = useState([]), [availability, setAvailability] = useState({}), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; const unsubscribe = onAuthStateChanged(auth, user => { if (!user) return; user.getIdToken().then(token => fetch('/api/teacher/shift-preferences', { headers: { Authorization: `Bearer ${token}` } })).then(response => response.json()).then(value => { if (!active) return; if (value.error) throw new Error(value.error); setPeriods(value.periods || []); setSubjectsSelected(value.preferences?.subjects || []); setGrades(value.preferences?.grades || []); setAvailability(value.preferences?.availability || {}); }).catch(error => { if (active) setNotice(error.message); }); }); return () => { active = false; unsubscribe(); }; }, []);
  const toggle = (values, value, setter) => setter(values.includes(value) ? values.filter(item => item !== value) : [...values, value]);
  const toggleSlot = (date, id) => setAvailability(old => { const values = old[date] || []; return { ...old, [date]: values.includes(id) ? values.filter(item => item !== id) : [...values, id] }; });
  const save = async () => { setBusy(true); try { const response = await fetch('/api/teacher/shift-preferences', { method: 'POST', headers: { Authorization: `Bearer ${await auth.currentUser?.getIdToken()}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ subjects: subjectsSelected, grades, availability }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setNotice('希望を保存しました。担当講師の割当は管理者が行います。'); } catch (error) { setNotice(error.message); } finally { setBusy(false); } };
  return <section className="teacher-shift-preferences"><h2>シフト希望</h2><p>出勤可能な日付・時間帯と指導できる教科・学年を登録してください。</p>{notice && <p role="status">{notice}</p>}<h3>指導可能教科</h3><div className="shift-option-row">{subjects.map(([code, label]) => <label key={code}><input type="checkbox" checked={subjectsSelected.includes(code)} onChange={() => toggle(subjectsSelected, code, setSubjectsSelected)}/>{label}</label>)}</div><h3>指導可能学年</h3><div className="shift-option-row">{Array.from({ length: 12 }, (_, index) => index + 1).map(grade => <label key={grade}><input type="checkbox" checked={grades.includes(grade)} onChange={() => toggle(grades, grade, setGrades)}/>{grade <= 6 ? `小${grade}` : grade <= 9 ? `中${grade - 6}` : `高${grade - 9}`}</label>)}</div><h3>出勤可能時間</h3><div className="shift-week-nav"><button onClick={() => setWeek(shiftDateAt(week, -7))}>← 前週</button><strong>{week}から</strong><button onClick={() => setWeek(shiftDateAt(week, 7))}>次週 →</button></div><div className="shift-availability-grid"><div className="shift-grid-head">時間</div>{weekdayNames.map((label, index) => <div className="shift-grid-head" key={label}>{shiftDateAt(week, index)}（{label}）</div>)}{periods.map(period => <div className="shift-grid-row" key={period.id}><strong>{period.startTime}〜{period.endTime}</strong>{weekdayNames.map((_, index) => { const date = shiftDateAt(week, index); return <label key={date}><input type="checkbox" checked={(availability[date] || []).includes(period.id)} onChange={() => toggleSlot(date, period.id)}/><span>出勤可</span></label>; })}</div>)}</div><button className="shift-preferences-save" disabled={busy} onClick={save}>{busy ? '保存中…' : 'シフト希望を保存'}</button></section>;
}
