'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { createUserWithEmailAndPassword, getAuth, signOut } from 'firebase/auth';
import '../../auth.css';

export default function TeacherSignup(){
  const router=useRouter(),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const submit=async event=>{event.preventDefault();if(busy)return;if(name.trim().length<2||password.length<8||password!==confirm)return setMessage('氏名、8文字以上のパスワード、確認用パスワードを確認してください。');setBusy(true);try{const auth=getAuth(),credential=await createUserWithEmailAndPassword(auth,email,password),token=await credential.user.getIdToken();const response=await fetch('/api/teacher/register',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({displayName:name})});const result=await response.json();if(!response.ok)throw new Error(result.error);await signOut(auth);setMessage('申請を受け付けました。教室の承認後にログインできます。');}catch(error){setMessage(error.code==='auth/email-already-in-use'?'このメールアドレスはすでに使用されています。':error.message);}finally{setBusy(false)}};
  return <main className="auth-shell auth-teacher"><section className="auth-card"><div className="brand-mark">C</div><p className="auth-eyebrow">TEACHER REQUEST</p><h1 className="auth-title">講師アカウント申請</h1><p className="auth-copy">ご本人のメールアドレスで登録してください。教室が承認した後に利用できます。</p><form className="auth-form" onSubmit={submit}><label className="auth-field"><span className="auth-label">氏名</span><input className="auth-input" value={name} onChange={e=>setName(e.target.value)}/></label><label className="auth-field"><span className="auth-label">メールアドレス</span><input className="auth-input" type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="auth-field"><span className="auth-label">パスワード（8文字以上）</span><input className="auth-input" type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="auth-field"><span className="auth-label">パスワード確認</span><input className="auth-input" type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>{message&&<p className="auth-message" role="status">{message}</p>}<button className="auth-button primary" disabled={busy}>{busy?'申請中…':'講師登録を申請'}</button><button type="button" className="auth-link" onClick={()=>router.push('/teacher/login')}>講師ログインへ戻る</button></form></section></main>;
}
