'use client';
import { useEffect, useState } from 'react';
import { auth } from '@/firebaseConfig';
import { BASE_TEST_TYPES } from '@/lib/scoreSubmissionPlan.mjs';
import { schoolDeviationFromTopPercent } from '@/lib/schoolDeviation.mjs';

const MAIN=['国語','社会','数学','理科','英語'],SUB=['音楽','美術','保体','技家'],blank=subjects=>Object.fromEntries(subjects.map(subject=>[subject,''])),ratings=subjects=>Object.fromEntries(subjects.map(subject=>[subject,3]));
export default function StaffScoreEntry({students=[],studentKey=''}){
  const [student,setStudent]=useState(''),[type,setType]=useState('exam'),[year,setYear]=useState(String(new Date().getFullYear())),[term,setTerm]=useState('1学期'),[testType,setTestType]=useState(BASE_TEST_TYPES[0]),[exam,setExam]=useState(()=>blank(MAIN)),[main,setMain]=useState(()=>ratings(MAIN)),[sub,setSub]=useState(()=>ratings(SUB)),[gradePercentile,setGradePercentile]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false);
  useEffect(()=>{if(studentKey)setStudent(studentKey)},[studentKey]);
  const save=async()=>{if(!student||saving)return;setSaving(true);setNotice('');try{const response=await fetch('/api/teacher/scores',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await auth.currentUser?.getIdToken()}`},body:JSON.stringify(type==='exam'?{student,type,year,term,testType,exam,gradePercentile}:{student,type,year,term,internalMain:main,internalSub:sub})}),result=await response.json();if(!response.ok)throw new Error(result.error);setNotice('成績を保存しました。管理者・生徒・保護者の画面にも同じデータが反映されます。');if(type==='exam')setExam(blank(MAIN))}catch(error){setNotice(error.message)}finally{setSaving(false)}};
  return <section className="staff-score-entry"><h2>成績入力</h2><p>管理者・生徒・保護者と同じ成績データへ登録します。</p>{!studentKey&&<label>生徒<select value={student} onChange={event=>setStudent(event.target.value)}><option value="">中学生を選択</option>{students.filter(item=>item.key?.startsWith('user_')&&Number(item.grade)>=7&&Number(item.grade)<=9).map(item=><option key={item.key} value={item.key}>{item.realName||item.name}</option>)}</select></label>}<div className="teacher-attendance"><button type="button" className={type==='exam'?'selected':''} onClick={()=>setType('exam')}>テスト</button><button type="button" className={type==='internal'?'selected':''} onClick={()=>setType('internal')}>通知表</button></div><div className="teacher-score-meta"><label>年度<input type="number" value={year} onChange={event=>setYear(event.target.value)}/></label><label>学期<select value={term} onChange={event=>setTerm(event.target.value)}>{['1学期','2学期','3学期'].map(value=><option key={value}>{value}</option>)}</select></label>{type==='exam'&&<label>テスト<select value={testType} onChange={event=>setTestType(event.target.value)}>{BASE_TEST_TYPES.map(value=><option key={value}>{value}</option>)}</select></label>}</div>{type==='exam'?<><div className="teacher-score-subjects">{MAIN.map(subject=><label key={subject}>{subject}<input type="number" min="0" max="100" value={exam[subject]} onChange={event=>setExam(old=>({...old,[subject]:event.target.value}))}/></label>)}</div><label>5計％（任意）<input type="number" min="0.1" max="99.9" step="0.1" value={gradePercentile} onChange={event=>setGradePercentile(event.target.value)}/><small>{gradePercentile?`校内推定偏差値 ${schoolDeviationFromTopPercent(gradePercentile)??'入力値を確認'}`:'入力すると校内推定偏差値を算出します'}</small></label></>:<div className="teacher-score-subjects">{[...MAIN,...SUB].map(subject=><label key={subject}>{subject}<select value={(MAIN.includes(subject)?main:sub)[subject]} onChange={event=>(MAIN.includes(subject)?setMain:setSub)(old=>({...old,[subject]:Number(event.target.value)}))}>{[1,2,3,4,5].map(value=><option key={value}>{value}</option>)}</select></label>)}</div>}{notice&&<p role="status">{notice}</p>}<button type="button" disabled={!student||saving} onClick={save}>{saving?'保存中…':'この成績を保存'}</button></section>;
}
