import { adminAuth,adminDb } from '@/lib/firebaseAdmin';
import { FieldPath } from 'firebase-admin/firestore';

export const dynamic='force-dynamic';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo'}).format(new Date());
const academicYear=date=>Number(date.slice(5,7))<=3?Number(date.slice(0,4))-1:Number(date.slice(0,4));

export async function GET(request){
  try{
    const token=request.headers.get('authorization')||'';if(!token.startsWith('Bearer '))return Response.json({error:'ログインしてください。'},{status:401});
    const authUser=await adminAuth.verifyIdToken(token.slice(7),true),params=new URL(request.url).searchParams,full=params.get('detail')==='full',year=Number(params.get('year'))||academicYear(today()),studentKey=`user_${authUser.uid}`;
    const[student,profile,calendar,manualDocs,courseDocs,interviewDocs]=await Promise.all([adminDb.collection('users').doc(authUser.uid).get(),adminDb.collection('studentProfiles').doc(studentKey).get(),adminDb.collection('adminLessonCalendars').doc(String(year)).get(),adminDb.collection('parentEvents').where('startDate','<=',`${year+1}-12-31`).limit(300).get(),adminDb.collection('courseSessions').where('studentKey','==',studentKey).get(),adminDb.collection('interviewSlots').where('studentKey','==',studentKey).get()]);
    if(!student.exists||student.data().active===false||student.data().enrollmentStatus==='withdrawn')return Response.json({error:'生徒情報を確認できません。'},{status:403});
    const data=student.data(),grade=Number(data.grade),school=String(profile.data()?.schoolName||data.schoolName||''),dates=calendar.data()?.dates||{},teachingDates=Object.keys(dates).filter(date=>dates[date]).sort(),yearStart=teachingDates[0]||`${year}-04-01`,yearEnd=teachingDates.at(-1)||`${year+1}-03-31`,weekdays=(data.lessonSchedule?.weekdays||data.weekdays||[]).map(Number),lessonSlots=data.lessonSchedule?.slots||data.lessonScheduleSlots||{},history=[...(data.lessonSchedule?.history||data.lessonScheduleHistory||[])].filter(item=>item.effectiveFrom).sort((a,b)=>String(a.effectiveFrom).localeCompare(String(b.effectiveFrom))),lessonStart=String(data.lessonSchedule?.startDate||data.lessonStartDate||data.enrollmentDate||'').slice(0,10);
    const weekdaysOn=date=>{if(!history.length)return weekdays;const past=history.filter(item=>item.effectiveFrom<=date).at(-1);return (past?.weekdays||(date<history[0].effectiveFrom?history[0].previousWeekdays:null)||weekdays).map(Number)},regular=teachingDates.filter(date=>(!lessonStart||date>=lessonStart)&&weekdaysOn(date).includes(new Date(`${date}T12:00:00+09:00`).getDay())).map(date=>{const day=String(new Date(`${date}T12:00:00+09:00`).getDay()),slot=lessonSlots[day]||{};return{id:`regular_${date}`,name:slot.subject?`通常授業（${slot.subject}）`:'通常授業',type:'lesson',startDate:date,endDate:date,startTime:slot.startTime||data.lessonSchedule?.startTime||data.lessonStartTime||'',subject:slot.subject||'',source:'schedule'}});
    let makeups=[];if(full){const snapshots=await Promise.all([adminDb.collection('adminLessonAttendance').doc(studentKey).collection('records').where(FieldPath.documentId(),'>=',yearStart).where(FieldPath.documentId(),'<=',yearEnd).limit(400).get(),...(grade>=7&&grade<=9?[1,2,3].map(term=>adminDb.collection('users').doc(authUser.uid).collection('lessonTerms').doc(`${year}_${term}`).collection('records').get()):[])]),map=new Map();snapshots.flatMap(snapshot=>snapshot.docs).forEach(doc=>{const value=doc.data();if((value.status||value.attendance)==='makeup')map.set(doc.id,{id:`makeup_${doc.id}`,name:'振替授業',type:'makeup',startDate:doc.id,endDate:doc.id,source:'attendance'})});makeups=[...map.values()];}
    const targeted=item=>item.targetType==='all'||!item.targetType||item.targetType==='grade'&&String(item.targetValue)===String(grade)||item.targetType==='school'&&String(item.targetValue)===school||item.targetType==='student'&&String(item.targetValue||'').split(',').map(value=>value.trim()).some(value=>value===studentKey||value===authUser.uid);
    const manual=manualDocs.docs.map(doc=>({id:doc.id,...doc.data()})).filter(item=>item.showStudent===true&&item.endDate>=yearStart&&targeted(item));
    const courses=courseDocs.docs.map(doc=>({id:`course_${doc.id}`,name:'講習授業',type:'course',startDate:doc.data().date,endDate:doc.data().date,startTime:doc.data().startTime||'',endTime:doc.data().endTime||'',detail:doc.data().subject||'',source:'courseSessions'})).filter(item=>item.startDate>=yearStart&&item.startDate<=yearEnd),interviews=interviewDocs.docs.filter(doc=>doc.data().reservationId).map(doc=>({id:`interview_${doc.id}`,name:'保護者面談',type:'interview',startDate:doc.data().date,endDate:doc.data().date,startTime:doc.data().startTime||'',endTime:doc.data().endTime||'',source:'interviewSlots'}));
    const events=[...regular,...makeups,...courses,...interviews,...manual].sort((a,b)=>a.startDate.localeCompare(b.startDate)||String(a.startTime).localeCompare(String(b.startTime)));
    return Response.json(full?{year,teachingDates,calendarEvents:events}:{items:events.filter(item=>(item.endDate||item.startDate)>=today()).slice(0,8)});
  }catch(error){return Response.json({error:error.message||'予定を取得できませんでした。'},{status:400})}
}
