'use client';
import { useEffect,useMemo,useState } from 'react';
import { auth } from '@/firebaseConfig';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo'}).format(new Date());
export default function LessonInputStatus(){
  const[date,setDate]=useState(today()),[data,setData]=useState(null),[filter,setFilter]=useState('action'),[error,setError]=useState('');
  useEffect(()=>{let active=true;setData(null);setError('');auth.currentUser?.getIdToken().then(token=>fetch(`/api/teacher/context?date=${date}`,{headers:{Authorization:`Bearer ${token}`}})).then(async response=>{const value=await response.json();if(!response.ok)throw new Error(value.error);if(active)setData(value)}).catch(error=>{if(active)setError(error.message)});return()=>{active=false}},[date]);
  const rows=useMemo(()=>{if(!data)return[];return data.students.filter(item=>item.scheduled).map(item=>{const saved=data.inputStatus?.[item.key],draft=data.draftStatus?.[item.key],missingFields=saved?.missingFields?.length?saved.missingFields:draft?.missingFields||[],state=saved?(missingFields.length?'incomplete':'saved'):draft?.missingFields?.length?'incomplete':draft?'draft':'missing';return{...item,state,missingFields}}).filter(item=>filter==='all'||filter==='action'&&item.state!=='saved'||filter===item.state)},[data,filter]);
  const counts=useMemo(()=>{const rows=(data?.students||[]).filter(item=>item.scheduled).map(item=>{const saved=data.inputStatus?.[item.key],draft=data.draftStatus?.[item.key];return saved?(saved.missingFields?.length?'incomplete':'saved'):draft?(draft.missingFields?.length?'incomplete':'draft'):'missing'});return{all:rows.length,saved:rows.filter(value=>value==='saved').length,draft:rows.filter(value=>value==='draft').length,missing:rows.filter(value=>value==='missing').length,incomplete:rows.filter(value=>value==='incomplete').length}},[data]);
  return <section className="lesson-input-status"><header><div><small>DAILY INPUT STATUS</small><h2>本日の入力状況</h2></div><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></header>{error&&<p role="alert">{error}</p>}<div className="lesson-status-counts"><button onClick={()=>setFilter('action')}><strong>{counts.missing+counts.draft+counts.incomplete}</strong><span>要対応</span></button><button onClick={()=>setFilter('missing')}><strong>{counts.missing}</strong><span>未入力</span></button><button onClick={()=>setFilter('draft')}><strong>{counts.draft}</strong><span>一時保存</span></button><button onClick={()=>setFilter('incomplete')}><strong>{counts.incomplete}</strong><span>必須不足</span></button><button onClick={()=>setFilter('saved')}><strong>{counts.saved}</strong><span>保存済み</span></button></div>{!data?<p>入力状況を読み込み中…</p>:<div className="lesson-status-list">{rows.map(item=><button key={item.key} onClick={()=>location.assign(`/admin/lesson-records?student=${encodeURIComponent(item.key)}&date=${date}${item.state==='draft'||item.state==='incomplete'?'&draft=1':''}`)}><span><strong>{item.name}</strong><small>{item.lessonStartTime||'時刻未設定'}{item.lessonSubject?`・${item.lessonSubject}`:''}</small></span><b data-state={item.state}>{item.state==='saved'?'保存済み':item.state==='missing'?'未入力':item.state==='incomplete'?`不足：${item.missingFields.join('・')}`:'一時保存'}</b></button>)}{!rows.length&&<p>該当する授業はありません。</p>}</div>}</section>;
}
