'use client';
import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut } from 'firebase/auth';
import { auth } from '@/firebaseConfig';
import '../../auth.css';

async function inviteApi(body, token) { const response=await fetch('/api/invite',{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error);return result; }
export default function InvitePage(){
  const {id}=useParams(),router=useRouter(),[secret,setSecret]=useState(''),[invite,setInvite]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[message,setMessage]=useState('招待情報を確認しています…'),[busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;const value=location.hash.slice(1);setSecret(value);signOut(auth).then(()=>inviteApi({action:'preview',id,secret:value})).then(data=>{if(active){setInvite(data);setMessage('')}}).catch(error=>{if(active)setMessage(error.message)});return()=>{active=false}},[id]);
  const register=async event=>{event.preventDefault();if(busy)return;if(!email||password.length<8)return setMessage('メールアドレスと8文字以上のパスワードを入力してください。');if(password!==confirm)return setMessage('確認用パスワードが一致しません。');setBusy(true);let user;try{let credential;try{credential=await createUserWithEmailAndPassword(auth,email,password)}catch(error){if(error.code!=='auth/email-already-in-use')throw error;credential=await signInWithEmailAndPassword(auth,email,password)}user=credential.user;const token=await user.getIdToken();await inviteApi({action:'claim',id,secret},token);setMessage('登録が完了しました。専用ログイン画面へ移動します。');await signOut(auth);router.replace(invite.role==='teacher'?'/teacher/login':invite.role==='parent'?'/parent/login':'/login');}catch(error){setMessage(error.message||'アカウントを登録できませんでした。');}finally{setBusy(false)}};
  const childLabel=(invite?.childNames||[]).join('さん、');
  const roleLabel={admin:'管理者',teacher:'講師',parent:'保護者'}[invite?.role]||'招待';
  return <main className={`auth-shell auth-${invite?.role||'parent'}`}><section className="auth-card"><div className="brand-mark">C</div><p className="auth-eyebrow">INVITATION</p><h1 className="auth-title">{roleLabel}アカウント登録</h1>{invite&&<p className="auth-copy">{invite.displayName} 様<br/>{invite.role==='parent'?`${childLabel||'お子さま'}さんと紐付けます。`:invite.role==='teacher'?'講師用画面を利用できます。':'管理者画面を利用できます。'}</p>}{message&&<p className={`auth-message ${invite?'error':''}`} role="status">{message}</p>}{invite&&<form className="auth-form" onSubmit={register}><label className="auth-field"><span className="auth-label">ご本人のメールアドレス</span><input className="auth-input" type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="auth-field"><span className="auth-label">パスワード（8文字以上）</span><input className="auth-input" type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="auth-field"><span className="auth-label">パスワード確認</span><input className="auth-input" type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button className="auth-button primary" disabled={busy}>{busy?'登録中…':'アカウントを登録'}</button><small className="auth-hint">招待リンクは登録完了後に使用できなくなります。</small></form>}</section></main>;
}
