import { FieldValue } from 'firebase-admin/firestore';
import { adminDb } from '@/lib/firebaseAdmin';
import { requireAdmin } from '@/lib/staffAccess';

export const dynamic='force-dynamic';
const id=value=>/^[A-Za-z0-9_-]{6,160}$/.test(value||'');
const date=value=>/^\d{4}-\d{2}-\d{2}$/.test(value||'');
const text=(value,max=160)=>String(value||'').trim().slice(0,max);
const whole=(value,min=0,max=10000000)=>{const number=Number(value);return Number.isFinite(number)?Math.max(min,Math.min(max,Math.floor(number))):min};
const list=async name=>(await adminDb.collection(name).get()).docs.map(doc=>({id:doc.id,...doc.data()}));

export async function GET(request){try{await requireAdmin(request);const[programs,applications,availability,sessions,periods,slots,users,elementary]=await Promise.all([list('coursePrograms'),list('courseApplications'),list('courseAvailability'),list('courseSessions'),list('interviewPeriods'),list('interviewSlots'),list('users'),list('adminStudents')]);const students=[...users.filter(item=>item.active!==false&&item.enrollmentStatus!=='withdrawn'&&Number(item.grade)>=7&&Number(item.grade)<=9).map(item=>({key:`user_${item.id}`,uid:item.id,name:item.realName||item.displayName||item.name||'名前未設定',grade:Number(item.grade)})),...elementary.filter(item=>item.active!==false&&item.enrollmentStatus!=='withdrawn').map(item=>({key:`elementary_${item.id}`,uid:item.id,name:item.name||item.realName||'名前未設定',grade:Number(item.grade)}))];const assignmentSnapshots=await Promise.all(programs.map(program=>adminDb.collection('coursePrograms').doc(program.id).collection('assignments').get())),assignments=[];assignmentSnapshots.forEach((snapshot,index)=>snapshot.docs.forEach(doc=>assignments.push({id:doc.id,programId:programs[index].id,...doc.data()})));return Response.json({programs:programs.sort((a,b)=>String(b.startDate||'').localeCompare(String(a.startDate||''))),applications,availability,sessions,assignments,periods,slots,students});}catch(error){return Response.json({error:error.message},{status:error.status||400})}}

export async function POST(request){try{const admin=await requireAdmin(request),body=await request.json(),now=FieldValue.serverTimestamp();
  if(body.action==='configureProgram'){if(!id(body.programId))throw new Error('講習を選択してください。');const mode=['fixed','variable'].includes(body.mode)?body.mode:'fixed',unitPrice=whole(body.unitPrice),courses=(body.courses||[]).slice(0,20).map(row=>({id:id(row.id)?row.id:crypto.randomUUID(),name:text(row.name,80),lessons:whole(row.lessons,1,100),price:whole(row.price)})).filter(row=>row.name);await adminDb.collection('coursePrograms').doc(body.programId).set({application:{enabled:body.enabled===true,mode,deadline:date(body.deadline)?body.deadline:'',unitPrice,courses},updatedBy:admin.uid,updatedAt:now},{merge:true});return Response.json({saved:true});}
  if(body.action==='saveSession'){if(!id(body.programId)||!/^user_[A-Za-z0-9_-]{6,128}$/.test(body.studentKey||'')||!date(body.date)||!/^\d{2}:\d{2}$/.test(body.startTime||'')||!/^\d{2}:\d{2}$/.test(body.endTime||'')||body.endTime<=body.startTime)throw new Error('講習・生徒・日時を確認してください。');const[program,application,availability,studentSessions]=await Promise.all([adminDb.collection('coursePrograms').doc(body.programId).get(),adminDb.collection('courseApplications').doc(`${body.programId}_${body.studentKey}`).get(),adminDb.collection('courseAvailability').doc(`${body.programId}_${body.studentKey}`).get(),adminDb.collection('courseSessions').where('studentKey','==',body.studentKey).get()]);if(!program.exists||!application.exists||application.data().status==='cancelled')throw new Error('有効な講習申込を確認できません。');const programData=program.data();if(programData.startDate&&body.date<programData.startDate||programData.endDate&&body.date>programData.endDate)throw new Error('講習期間内の日付を選択してください。');if((availability.data()?.entries||[]).some(item=>item.date===body.date&&body.startTime<item.endTime&&body.endTime>item.startTime))throw new Error('保護者が来校不可として登録した時間です。');const docId=id(body.id)?body.id:crypto.randomUUID(),other=studentSessions.docs.filter(doc=>doc.id!==docId&&doc.data().programId===body.programId);if(other.length>=Number(application.data().lessons||0))throw new Error('申込回数を超えて配置できません。');if(other.some(doc=>{const row=doc.data();return row.date===body.date&&body.startTime<row.endTime&&body.endTime>row.startTime}))throw new Error('この生徒には同じ時間帯の授業が既にあります。');const ref=adminDb.collection('courseSessions').doc(docId),old=await ref.get();await ref.set({programId:body.programId,studentKey:body.studentKey,date:body.date,startTime:body.startTime,endTime:body.endTime,subject:text(body.subject,40),status:'scheduled',createdAt:old.data()?.createdAt||now,createdBy:old.data()?.createdBy||admin.uid,updatedAt:now,updatedBy:admin.uid},{merge:true});return Response.json({saved:true,id:docId});}
  if(body.action==='saveInterviewPeriod'){if(!text(body.name,100)||!date(body.startDate)||!date(body.endDate)||body.endDate<body.startDate)throw new Error('面談期間を確認してください。');const docId=id(body.id)?body.id:crypto.randomUUID(),ref=adminDb.collection('interviewPeriods').doc(docId),old=await ref.get();await ref.set({name:text(body.name,100),startDate:body.startDate,endDate:body.endDate,active:body.active!==false,createdAt:old.data()?.createdAt||now,updatedAt:now,updatedBy:admin.uid},{merge:true});return Response.json({saved:true,id:docId});}
  if(body.action==='saveInterviewSlot'){if(!id(body.periodId)||!date(body.date)||!/^\d{2}:\d{2}$/.test(body.startTime||'')||!/^\d{2}:\d{2}$/.test(body.endTime||'')||body.endTime<=body.startTime)throw new Error('面談枠を確認してください。');const[period,sameDate]=await Promise.all([adminDb.collection('interviewPeriods').doc(body.periodId).get(),adminDb.collection('interviewSlots').where('date','==',body.date).get()]);if(!period.exists||body.date<period.data().startDate||body.date>period.data().endDate)throw new Error('面談期間内の日付を選択してください。');const docId=id(body.id)?body.id:crypto.randomUUID();if(sameDate.docs.some(doc=>doc.id!==docId&&body.startTime<doc.data().endTime&&body.endTime>doc.data().startTime))throw new Error('重複する面談枠があります。');const ref=adminDb.collection('interviewSlots').doc(docId),old=await ref.get();if(old.data()?.reservationId)throw new Error('予約済みの枠は変更できません。');await ref.set({periodId:body.periodId,date:body.date,startTime:body.startTime,endTime:body.endTime,available:body.available!==false,reservationId:null,parentUid:null,studentKey:null,createdAt:old.data()?.createdAt||now,updatedAt:now,updatedBy:admin.uid},{merge:true});return Response.json({saved:true,id:docId});}
  throw new Error('操作が正しくありません。');
}catch(error){return Response.json({error:error.message},{status:error.status||400})}}

export async function DELETE(request){try{await requireAdmin(request);const p=new URL(request.url).searchParams,type=p.get('type'),docId=p.get('id'),collections={session:'courseSessions',period:'interviewPeriods',slot:'interviewSlots'};if(!collections[type]||!id(docId))throw new Error('削除対象を確認してください。');const ref=adminDb.collection(collections[type]).doc(docId),snap=await ref.get();if(type==='slot'&&snap.data()?.reservationId)throw new Error('予約済みの枠は削除できません。');if(type==='period'&&(await adminDb.collection('interviewSlots').where('periodId','==',docId).limit(1).get()).size)throw new Error('面談枠が残っています。先に枠を削除してください。');await ref.delete();return Response.json({deleted:true});}catch(error){return Response.json({error:error.message},{status:error.status||400})}}
