import { FieldValue } from 'firebase-admin/firestore';
import { adminDb } from '@/lib/firebaseAdmin';
import { requireAdmin } from '@/lib/staffAccess';

export const dynamic='force-dynamic';
const id=value=>/^[A-Za-z0-9_-]{6,160}$/.test(value||'');
const date=value=>/^\d{4}-\d{2}-\d{2}$/.test(value||'');
const text=(value,max=160)=>String(value||'').trim().slice(0,max);
const whole=(value,min=0,max=10000000)=>{const number=Number(value);return Number.isFinite(number)?Math.max(min,Math.min(max,Math.floor(number))):min};
const list=async name=>(await adminDb.collection(name).get()).docs.map(doc=>({id:doc.id,...doc.data()}));
const matching=async(name,field,value)=>(await adminDb.collection(name).where(field,'==',value).get()).docs.map(doc=>({id:doc.id,...doc.data()}));

export async function GET(request){try{await requireAdmin(request);const programId=new URL(request.url).searchParams.get('programId'),courseMode=id(programId),[programDocs,applications,availability,sessions,periods,slots,users,elementary]=await Promise.all([courseMode?adminDb.collection('coursePrograms').doc(programId).get():Promise.resolve(null),courseMode?matching('courseApplications','programId',programId):Promise.resolve([]),courseMode?matching('courseAvailability','programId',programId):Promise.resolve([]),courseMode?matching('courseSessions','programId',programId):Promise.resolve([]),courseMode?Promise.resolve([]):list('interviewPeriods'),courseMode?Promise.resolve([]):list('interviewSlots'),list('users'),list('adminStudents')]),programs=programDocs?.exists?[{id:programDocs.id,...programDocs.data()}]:[],students=[...users.filter(item=>item.active!==false&&item.enrollmentStatus!=='withdrawn'&&Number(item.grade)>=7&&Number(item.grade)<=9).map(item=>({key:`user_${item.id}`,uid:item.id,name:item.realName||item.displayName||item.name||'名前未設定',grade:Number(item.grade)})),...elementary.filter(item=>item.active!==false&&item.enrollmentStatus!=='withdrawn').map(item=>({key:`elementary_${item.id}`,uid:item.id,name:item.name||item.realName||'名前未設定',grade:Number(item.grade)}))],assignments=[];if(courseMode&&programDocs?.exists){const snapshot=await programDocs.ref.collection('assignments').get();snapshot.docs.forEach(doc=>assignments.push({id:doc.id,programId,...doc.data()}))}return Response.json({programs,applications,availability,sessions,assignments,periods,slots,students});}catch(error){return Response.json({error:error.message},{status:error.status||400})}}

export async function POST(request){try{const admin=await requireAdmin(request),body=await request.json(),now=FieldValue.serverTimestamp();
  if(body.action==='configureInterviewGrid'){
    if(!id(body.periodId))throw new Error('面談期間を選択してください。');
    const periodRef=adminDb.collection('interviewPeriods').doc(body.periodId),period=await periodRef.get();
    if(!period.exists)throw new Error('面談期間が見つかりません。');
    const timeSlots=(body.timeSlots||[]).slice(0,12).map(row=>({id:id(row.id)?row.id:crypto.randomUUID(),startTime:text(row.startTime,5),endTime:text(row.endTime,5)}));
    if(!timeSlots.length||timeSlots.some(row=>!/^[0-2][0-9]:[0-5][0-9]$/.test(row.startTime)||!/^[0-2][0-9]:[0-5][0-9]$/.test(row.endTime)||row.endTime<=row.startTime))throw new Error('面談時間帯を確認してください。');
    const dates=[];for(let cursor=new Date(`${period.data().startDate}T12:00:00+09:00`),end=new Date(`${period.data().endDate}T12:00:00+09:00`);cursor<=end;cursor.setDate(cursor.getDate()+1))dates.push(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo'}).format(cursor));
    if(dates.length>93)throw new Error('面談期間は93日以内で設定してください。');
    const existing=await adminDb.collection('interviewSlots').where('periodId','==',body.periodId).get(),existingMap=new Map(existing.docs.map(doc=>[`${doc.data().date}_${doc.data().startTime}_${doc.data().endTime}`,doc]));
    for(const day of dates)for(const time of timeSlots){const old=existingMap.get(`${day}_${time.startTime}_${time.endTime}`),available=body.availability?.[`${day}_${time.id}`]!==false;if(old?.data().reservationId&&!available)throw new Error(`${day} ${time.startTime}は予約済みのため×にできません。`)}
    const batch=adminDb.bulkWriter(),activeIds=new Set();
    for(const day of dates)for(const time of timeSlots){const key=`${day}_${time.startTime}_${time.endTime}`,old=existingMap.get(key),docId=old?.id||`${body.periodId}_${day.replaceAll('-','')}_${time.startTime.replace(':','')}`,ref=adminDb.collection('interviewSlots').doc(docId),available=body.availability?.[`${day}_${time.id}`]!==false;activeIds.add(docId);batch.set(ref,{periodId:body.periodId,date:day,startTime:time.startTime,endTime:time.endTime,available,reservationId:old?.data().reservationId||null,parentUid:old?.data().parentUid||null,studentKey:old?.data().studentKey||null,createdAt:old?.data().createdAt||now,updatedAt:now,updatedBy:admin.uid},{merge:true});}
    existing.docs.filter(doc=>!activeIds.has(doc.id)&&!doc.data().reservationId).forEach(doc=>batch.set(doc.ref,{available:false,updatedAt:now,updatedBy:admin.uid},{merge:true}));
    batch.set(periodRef,{timeSlots,updatedAt:now,updatedBy:admin.uid},{merge:true});await batch.close();return Response.json({saved:true});
  }
  if(body.action==='configureProgram'){if(!id(body.programId))throw new Error('講習を選択してください。');const mode=['fixed','variable'].includes(body.mode)?body.mode:'fixed',unitPrice=whole(body.unitPrice),courses=(body.courses||[]).slice(0,20).map(row=>({id:id(row.id)?row.id:crypto.randomUUID(),name:text(row.name,80),lessons:whole(row.lessons,1,100),price:whole(row.price)})).filter(row=>row.name),document=body.document&&/^parentDocuments\/[A-Za-z0-9-]+\.pdf$/.test(body.document.storagePath||'')?{storagePath:body.document.storagePath,fileName:text(body.document.fileName,120)}:null;await adminDb.collection('coursePrograms').doc(body.programId).set({application:{enabled:body.enabled===true,mode,deadline:date(body.deadline)?body.deadline:'',unitPrice,courses,document},updatedBy:admin.uid,updatedAt:now},{merge:true});return Response.json({saved:true});}
  if(body.action==='saveSession'){if(!id(body.programId)||!/^user_[A-Za-z0-9_-]{6,128}$/.test(body.studentKey||'')||!date(body.date)||!/^\d{2}:\d{2}$/.test(body.startTime||'')||!/^\d{2}:\d{2}$/.test(body.endTime||'')||body.endTime<=body.startTime)throw new Error('講習・生徒・日時を確認してください。');const[program,application,availability,studentSessions]=await Promise.all([adminDb.collection('coursePrograms').doc(body.programId).get(),adminDb.collection('courseApplications').doc(`${body.programId}_${body.studentKey}`).get(),adminDb.collection('courseAvailability').doc(`${body.programId}_${body.studentKey}`).get(),adminDb.collection('courseSessions').where('studentKey','==',body.studentKey).get()]);if(!program.exists||!application.exists||application.data().status==='cancelled')throw new Error('有効な講習申込を確認できません。');const programData=program.data();if(programData.startDate&&body.date<programData.startDate||programData.endDate&&body.date>programData.endDate)throw new Error('講習期間内の日付を選択してください。');if((availability.data()?.entries||[]).some(item=>item.date===body.date&&body.startTime<item.endTime&&body.endTime>item.startTime))throw new Error('保護者が来校不可として登録した時間です。');const docId=id(body.id)?body.id:crypto.randomUUID(),other=studentSessions.docs.filter(doc=>doc.id!==docId&&doc.data().programId===body.programId);if(other.length>=Number(application.data().lessons||0))throw new Error('申込回数を超えて配置できません。');if(other.some(doc=>{const row=doc.data();return row.date===body.date&&body.startTime<row.endTime&&body.endTime>row.startTime}))throw new Error('この生徒には同じ時間帯の授業が既にあります。');const ref=adminDb.collection('courseSessions').doc(docId),old=await ref.get();await ref.set({programId:body.programId,studentKey:body.studentKey,date:body.date,startTime:body.startTime,endTime:body.endTime,subject:text(body.subject,40),status:'scheduled',createdAt:old.data()?.createdAt||now,createdBy:old.data()?.createdBy||admin.uid,updatedAt:now,updatedBy:admin.uid},{merge:true});return Response.json({saved:true,id:docId});}
  if(body.action==='saveInterviewPeriod'){if(!text(body.name,100)||!date(body.startDate)||!date(body.endDate)||body.endDate<body.startDate)throw new Error('面談期間を確認してください。');const docId=id(body.id)?body.id:crypto.randomUUID(),ref=adminDb.collection('interviewPeriods').doc(docId),old=await ref.get();await ref.set({name:text(body.name,100),startDate:body.startDate,endDate:body.endDate,active:body.active!==false,createdAt:old.data()?.createdAt||now,updatedAt:now,updatedBy:admin.uid},{merge:true});return Response.json({saved:true,id:docId});}
  if(body.action==='saveInterviewSlot'){if(!id(body.periodId)||!date(body.date)||!/^\d{2}:\d{2}$/.test(body.startTime||'')||!/^\d{2}:\d{2}$/.test(body.endTime||'')||body.endTime<=body.startTime)throw new Error('面談枠を確認してください。');const[period,sameDate]=await Promise.all([adminDb.collection('interviewPeriods').doc(body.periodId).get(),adminDb.collection('interviewSlots').where('date','==',body.date).get()]);if(!period.exists||body.date<period.data().startDate||body.date>period.data().endDate)throw new Error('面談期間内の日付を選択してください。');const docId=id(body.id)?body.id:crypto.randomUUID();if(sameDate.docs.some(doc=>doc.id!==docId&&body.startTime<doc.data().endTime&&body.endTime>doc.data().startTime))throw new Error('重複する面談枠があります。');const ref=adminDb.collection('interviewSlots').doc(docId),old=await ref.get();if(old.data()?.reservationId)throw new Error('予約済みの枠は変更できません。');await ref.set({periodId:body.periodId,date:body.date,startTime:body.startTime,endTime:body.endTime,available:body.available!==false,reservationId:null,parentUid:null,studentKey:null,createdAt:old.data()?.createdAt||now,updatedAt:now,updatedBy:admin.uid},{merge:true});return Response.json({saved:true,id:docId});}
  throw new Error('操作が正しくありません。');
}catch(error){return Response.json({error:error.message},{status:error.status||400})}}

export async function DELETE(request){try{await requireAdmin(request);const p=new URL(request.url).searchParams,type=p.get('type'),docId=p.get('id'),collections={session:'courseSessions',period:'interviewPeriods',slot:'interviewSlots'};if(!collections[type]||!id(docId))throw new Error('削除対象を確認してください。');const ref=adminDb.collection(collections[type]).doc(docId),snap=await ref.get();if(type==='slot'&&snap.data()?.reservationId)throw new Error('予約済みの枠は削除できません。');if(type==='period'&&(await adminDb.collection('interviewSlots').where('periodId','==',docId).limit(1).get()).size)throw new Error('面談枠が残っています。先に枠を削除してください。');await ref.delete();return Response.json({deleted:true});}catch(error){return Response.json({error:error.message},{status:error.status||400})}}
