'use client';
import { useEffect,useMemo,useState } from 'react';
import { onAuthStateChanged } from 'firebase/auth';
import { auth } from '@/firebaseConfig';
import './student-calendar.css';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo'}).format(new Date());
const group=type=>['lesson','makeup'].includes(type)?'lesson':type==='course'?'course':['school','exam'].includes(type)?'school':type==='interview'?'interview':'classroom';
export default function StudentCalendar(){const[data,setData]=useState(null),[month,setMonth]=useState(today().slice(0,7)),[selected,setSelected]=useState(today()),[error,setError]=useState('');useEffect(()=>onAuthStateChanged(auth,async user=>{if(!user)return location.href='/login';try{const response=await fetch('/api/student/events?detail=full',{headers:{Authorization:`Bearer ${await user.getIdToken()}`}}),value=await response.json();if(!response.ok)throw new Error(value.error);setData(value)}catch(error){setError(error.message)}}),[]);const months=useMemo(()=>{const values=new Set((data?.teachingDates||[]).map(value=>value.slice(0,7)));(data?.calendarEvents||[]).forEach(item=>values.add(item.startDate.slice(0,7)));return[...values].sort()},[data]),current=months.includes(month)?month:months[0],events=data?.calendarEvents||[],dayEvents=events.filter(item=>item.startDate<=selected&&(item.endDate||item.startDate)>=selected),upcoming=events.filter(item=>(item.endDate||item.startDate)>=today()).slice(0,8);if(error)return <main className="student-calendar-page"><a href="/mypage">← マイページ</a><p role="alert">{error}</p></main>;if(!data)return <main className="student-calendar-page"><p>予定を読み込んでいます…</p></main>;const index=months.indexOf(current);return <main className="student-calendar-page"><header><a href="/mypage">← マイページ</a><small>MY SCHEDULE</small><h1>授業カレンダー</h1><p>授業・講習・学校行事・教室行事・面談をまとめて確認できます。</p></header><nav><button disabled={index<=0} onClick={()=>setMonth(months[index-1])}>‹</button><select value={current} onChange={event=>setMonth(event.target.value)}>{months.map(value=><option key={value} value={value}>{value.replace('-','年 ')}月</option>)}</select><button disabled={index>=months.length-1} onClick={()=>setMonth(months[index+1])}>›</button></nav>{current&&<Month month={current} events={events} teaching={new Set(data.teachingDates)} selected={selected} onSelect={setSelected}/>}<div className="student-calendar-legend">{[['lesson','通常授業'],['course','講習授業'],['school','学校行事'],['classroom','教室行事'],['interview','面談']].map(([id,label])=><span className={id} key={id}>{label}</span>)}</div><section><h2>{selected.replaceAll('-',' / ')} の予定</h2>{dayEvents.length?dayEvents.map(item=><article key={item.id}><i className={group(item.type)}/><div><strong>{item.name}</strong><small>{item.detail||''}</small></div><time>{item.startTime}{item.endTime?`〜${item.endTime}`:''}</time></article>):<p>この日の予定はありません。</p>}</section><section><h2>今後の予定</h2>{upcoming.map(item=><article key={item.id}><time>{item.startDate.replaceAll('-',' / ')}</time><div><strong>{item.name}</strong><small>{item.detail||''}</small></div></article>)}</section></main>}
function Month({month,events,teaching,selected,onSelect}){const[year,value]=month.split('-').map(Number),first=new Date(year,value-1,1).getDay(),count=new Date(year,value,0).getDate();return <section className="student-calendar"><div className="week">{'日月火水木金土'.split('').map(day=><b key={day}>{day}</b>)}</div><div className="days">{Array.from({length:first},(_,index)=><i key={index}/>)}{Array.from({length:count},(_,index)=>{const day=index+1,id=`${year}-${String(value).padStart(2,'0')}-${String(day).padStart(2,'0')}`,items=events.filter(item=>item.startDate<=id&&(item.endDate||item.startDate)>=id);return <button className={`${teaching.has(id)?'open ':''}${selected===id?'selected':''}`} key={id} onClick={()=>onSelect(id)}><time>{day}</time><span>{[...new Set(items.map(item=>group(item.type)))].map(type=><i className={type} key={type}/>)}</span></button>})}</div></section>}
