'use client';
import { useEffect, useMemo, useState } from 'react';
import { auth } from '@/firebaseConfig';
import { SHIFT_PERIODS } from '@/lib/weeklyShifts';
import './course-operations.css';
import './course-operation-tabs.css';

const blankCourse = () => ({ id: crypto.randomUUID(), name: '', lessons: 1, price: 0 });
const blankPlan = () => ({ studentKey: '', date: '', startTime: '13:20', endTime: '14:50', subject: '', subjectCode: '', teacherUid: '' });
const subjects = [['', '教科を選択'], ['japanese', '国語'], ['math', '数学'], ['english', '英語'], ['science', '理科'], ['social', '社会'], ['other', 'その他']];
const statusLabel = { applied: '申込済', cancelled: '取消', scheduling: '日程作成中', confirmed: '確定' };

export default function CourseOperations({ programId }) {
  const [data, setData] = useState(null), [plansData, setPlansData] = useState({ plans: [], teachers: [] }), [notice, setNotice] = useState(''), [view, setView] = useState('application'), [busy, setBusy] = useState(false);
  const [mode, setMode] = useState('fixed'), [enabled, setEnabled] = useState(false), [deadline, setDeadline] = useState(''), [unitPrice, setUnitPrice] = useState(5000), [courses, setCourses] = useState([blankCourse()]), [document, setDocument] = useState(null), [uploading, setUploading] = useState(false), [plan, setPlan] = useState(blankPlan()), [counts, setCounts] = useState({});
  const api = async (path, body) => { const response = await fetch(path, { method: body ? 'POST' : 'GET', headers: { Authorization: `Bearer ${await auth.currentUser?.getIdToken()}`, ...(body ? { 'Content-Type': 'application/json' } : {}) }, ...(body ? { body: JSON.stringify({ ...body, programId }) } : {}) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || '通信に失敗しました。'); return result; };
  const load = async () => { const [value, planValue] = await Promise.all([api(`/api/admin/family-services?programId=${encodeURIComponent(programId)}`), api(`/api/admin/course-plans?programId=${encodeURIComponent(programId)}`)]); setData(value); setPlansData(planValue); const setting = value.programs.find(item => item.id === programId)?.application; if (setting) { setMode(setting.mode || 'fixed'); setEnabled(setting.enabled === true); setDeadline(setting.deadline || ''); setUnitPrice(setting.unitPrice || 0); setCourses(setting.courses?.length ? setting.courses : [blankCourse()]); setDocument(setting.document || null); } };
  useEffect(() => { if (programId) load().catch(error => setNotice(error.message)); }, [programId]);
  const applications = (data?.applications || []).filter(item => item.programId === programId), availability = data?.availability || [], students = data?.students || [], plans = plansData.plans || [];
  const name = key => students.find(item => item.key === key)?.name || key;
  const teacherName = uid => plansData.teachers.find(item => item.uid === uid)?.name || uid || '未割当';
  const countsByStudent = useMemo(() => Object.fromEntries(applications.map(item => [item.studentKey, { confirmed: plans.filter(row => row.studentKey === item.studentKey && row.status === 'confirmed').length, total: Number(item.confirmedLessons || 0), draft: plans.filter(row => row.studentKey === item.studentKey && row.status === 'draft').length }])), [applications, plans]);
  const post = async (path, body) => { setBusy(true); try { await api(path, body); await load(); setNotice('保存しました。'); if (body.action === 'savePlan') setPlan(blankPlan()); } catch (error) { setNotice(error.message); } finally { setBusy(false); } };
  const upload = async file => { setUploading(true); try { const form = new FormData(); form.append('file', file); const response = await fetch('/api/admin/parent-documents', { method: 'POST', headers: { Authorization: `Bearer ${await auth.currentUser?.getIdToken()}` }, body: form }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setDocument(result); setNotice('PDFを読み込みました。申込設定を保存してください。'); } catch (error) { setNotice(error.message); } finally { setUploading(false); } };
  const availablePeriods = SHIFT_PERIODS;
  if (!programId) return null;
  return <section className="course-operations course-card"><header><div><span>APPLICATION & SCHEDULE</span><h2>講習申込・日程管理</h2></div></header>{notice && <p role="status">{notice}</p>}
    <nav className="course-operation-tabs"><button className={view === 'application' ? 'active' : ''} onClick={() => setView('application')}>講習設定・申込</button><button className={view === 'schedule' ? 'active' : ''} onClick={() => setView('schedule')}>日程調整</button><button className={view === 'progress' ? 'active' : ''} onClick={() => setView('progress')}>確定・進捗</button></nav>
    {view === 'application' && <><div className="operation-grid"><label><input type="checkbox" checked={enabled} onChange={event => setEnabled(event.target.checked)}/>申込受付を公開</label><label>申込期限<input type="date" value={deadline} onChange={event => setDeadline(event.target.value)}/></label><label>方式<select value={mode} onChange={event => setMode(event.target.value)}><option value="fixed">固定コース</option><option value="variable">回数選択型</option></select></label>
      {mode === 'variable' ? <label>1コマ単価<input type="number" min="0" value={unitPrice} onChange={event => setUnitPrice(event.target.value)}/></label> : <div className="course-price-list">{courses.map((item, index) => <div key={item.id}><input placeholder="コース名" value={item.name} onChange={event => setCourses(old => old.map((row, i) => i === index ? { ...row, name: event.target.value } : row))}/><input aria-label="授業回数" type="number" min="1" value={item.lessons} onChange={event => setCourses(old => old.map((row, i) => i === index ? { ...row, lessons: event.target.value } : row))}/><input aria-label="料金" type="number" min="0" value={item.price} onChange={event => setCourses(old => old.map((row, i) => i === index ? { ...row, price: event.target.value } : row))}/><button onClick={() => setCourses(old => old.filter((_, i) => i !== index))}>削除</button></div>)}<button onClick={() => setCourses(old => [...old, blankCourse()])}>＋コース</button></div>}
      <label className="course-document-picker"><span>{uploading ? '読込中…' : document?.fileName || '講習案内PDFを選択'}</span><input type="file" accept="application/pdf,.pdf" disabled={uploading} onChange={event => event.target.files?.[0] && upload(event.target.files[0])}/></label><button className="primary" disabled={busy} onClick={() => post('/api/admin/family-services', { action: 'configureProgram', enabled, deadline, mode, unitPrice, courses, document })}>申込設定を保存</button></div>
      <h3>申込と受講コマ数の確定</h3><div className="application-table">{applications.filter(item => item.status !== 'cancelled').map(item => <article key={item.id}><strong>{name(item.studentKey)}</strong><span>申込 {item.lessons}コマ／{Number(item.total || 0).toLocaleString()}円</span><b>{statusLabel[item.status] || item.status}</b><label>受講コマ数<input type="number" min="1" max="100" value={counts[item.studentKey] ?? item.confirmedLessons ?? item.lessons} onChange={event => setCounts(old => ({ ...old, [item.studentKey]: event.target.value }))}/></label><button disabled={busy} onClick={() => post('/api/admin/course-plans', { action: 'confirmCount', studentKey: item.studentKey, lessons: counts[item.studentKey] ?? item.confirmedLessons ?? item.lessons })}>{item.countConfirmedAt ? 'コマ数を更新' : 'コマ数を確定'}</button></article>)}</div></>}
    {view === 'schedule' && <><p>コマ数を確定した生徒の日程を配置し、講師を手動で指定します。管理者が確認・確定するまで保護者やシフトには公開されません。</p><div className="session-form"><select value={plan.studentKey} onChange={event => setPlan({ ...plan, studentKey: event.target.value })}><option value="">生徒を選択</option>{applications.filter(item => item.status !== 'cancelled' && item.countConfirmedAt).map(item => <option key={item.studentKey} value={item.studentKey}>{name(item.studentKey)}（残り{Math.max(0, Number(item.confirmedLessons || 0) - (countsByStudent[item.studentKey]?.confirmed || 0) - (countsByStudent[item.studentKey]?.draft || 0))}）</option>)}</select><input type="date" value={plan.date} onChange={event => setPlan({ ...plan, date: event.target.value })}/><select value={plan.startTime} onChange={event => { const period = SHIFT_PERIODS.find(item => item.startTime === event.target.value); setPlan({ ...plan, startTime: period.startTime, endTime: period.endTime }); }}>{availablePeriods.map(item => <option key={item.id} value={item.startTime}>{item.startTime}〜{item.endTime}</option>)}</select><select value={plan.subjectCode} onChange={event => { const code = event.target.value; setPlan({ ...plan, subjectCode: code, subject: subjects.find(([value]) => value === code)?.[1] || '' }); }}>{subjects.map(([code, label]) => <option key={code} value={code}>{label}</option>)}</select>{plan.subjectCode === 'other' && <input placeholder="教科名" value={plan.subject} onChange={event => setPlan({ ...plan, subject: event.target.value })}/>}<select value={plan.teacherUid} onChange={event => setPlan({ ...plan, teacherUid: event.target.value })}><option value="">担当講師を選択</option>{plansData.teachers.map(item => <option key={item.uid} value={item.uid}>{item.name}</option>)}</select><button className="primary" disabled={busy} onClick={() => post('/api/admin/course-plans', { action: 'savePlan', ...plan })}>日程を下書き保存</button></div><div className="session-list">{plans.map(item => <article key={item.id}><time>{item.date} {item.startTime}〜{item.endTime}</time><strong>{name(item.studentKey)}</strong><span>{item.subject}／{teacherName(item.teacherUid)}</span><b>{item.status === 'confirmed' ? '確定済み' : '確認待ち'}</b>{item.status === 'draft' && <button disabled={busy || !item.teacherUid} onClick={() => post('/api/admin/course-plans', { action: 'confirmPlan', id: item.id })}>確認して確定</button>}<button disabled={busy} onClick={() => { if (confirm('この講習日程を削除しますか？')) post('/api/admin/course-plans', { action: 'deletePlan', id: item.id }); }}>削除</button></article>)}</div></>}
    {view === 'progress' && <><div className="application-table">{applications.filter(item => item.status !== 'cancelled').map(item => { const count = countsByStudent[item.studentKey]; return <article key={item.id}><strong>{name(item.studentKey)}</strong><span>{count.total ? `${count.total}コマ中${count.confirmed}コマ確定／残り${Math.max(0, count.total - count.confirmed)}コマ` : 'コマ数未確定'}</span><small>下書き {count.draft}件／不可時間 {(availability.find(row => row.studentKey === item.studentKey)?.entries || []).length}件</small></article>; })}</div><p>確定した講習日程は、<a href="/admin/shifts">講師シフト</a>の「確定した講習を反映」から対象週へ取り込みます。</p></>}
  </section>;
}
