'use client';
import { useEffect, useMemo, useState } from 'react';
import { auth } from '@/firebaseConfig';
import './course-operations.css';

const blankCourse=()=>({id:crypto.randomUUID(),name:'',lessons:1,price:0});
const blankSession=()=>({studentKey:'',date:'',startTime:'',endTime:'',subject:''});
const statusLabel={applied:'申込済',scheduling:'日程作成中',confirmed:'確定',changeRequested:'変更希望',cancelled:'取消'};

export default function CourseOperations({programId}){
  const [data,setData]=useState(null),[notice,setNotice]=useState(''),[mode,setMode]=useState('fixed'),[enabled,setEnabled]=useState(false),[deadline,setDeadline]=useState(''),[unitPrice,setUnitPrice]=useState(5000),[courses,setCourses]=useState([blankCourse()]),[session,setSession]=useState(blankSession());
  const api=async(options={})=>{const response=await fetch('/api/admin/family-services',{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${await auth.currentUser?.getIdToken()}`}}),result=await response.json();if(!response.ok)throw new Error(result.error);return result};
  const load=()=>api().then(value=>{setData(value);const setting=value.programs.find(item=>item.id===programId)?.application;if(setting){setMode(setting.mode||'fixed');setEnabled(setting.enabled===true);setDeadline(setting.deadline||'');setUnitPrice(setting.unitPrice||0);setCourses(setting.courses?.length?setting.courses:[blankCourse()])}}).catch(error=>setNotice(error.message));
  useEffect(()=>{load()},[programId]);
  const applications=(data?.applications||[]).filter(item=>item.programId===programId),sessions=(data?.sessions||[]).filter(item=>item.programId===programId).sort((a,b)=>a.date.localeCompare(b.date)),availability=(data?.availability||[]).filter(item=>item.programId===programId),assignments=(data?.assignments||[]).filter(item=>item.programId===programId),students=data?.students||[];
  const name=key=>students.find(item=>item.key===key)?.name||key;
  const capacity=useMemo(()=>sessions.reduce((map,item)=>{const key=`${item.date}_${item.startTime}`;map[key]=(map[key]||0)+1;return map},{}),[sessions]);
  const post=async body=>{try{await api({method:'POST',body:JSON.stringify(body)});setNotice('保存しました。');await load()}catch(error){setNotice(error.message)}};
  const remove=async(type,id)=>{if(!confirm('削除しますか？'))return;const response=await fetch(`/api/admin/family-services?type=${type}&id=${id}`,{method:'DELETE',headers:{Authorization:`Bearer ${await auth.currentUser?.getIdToken()}`}}),result=await response.json();setNotice(response.ok?'削除しました。':result.error);if(response.ok)load()};
  if(!programId)return null;
  return <section className="course-operations course-card">
    <header><div><span>APPLICATION & SCHEDULE</span><h2>講習申込・日程作成</h2></div></header>{notice&&<p role="status">{notice}</p>}
    <details open><summary>保護者向け申込設定</summary><div className="operation-grid">
      <label><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>申込受付を公開</label><label>申込期限<input type="date" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label><label>方式<select value={mode} onChange={e=>setMode(e.target.value)}><option value="fixed">固定コース</option><option value="variable">回数選択型</option></select></label>
      {mode==='variable'?<label>1コマ単価<input type="number" min="0" value={unitPrice} onChange={e=>setUnitPrice(e.target.value)}/></label>:<div className="course-price-list">{courses.map((item,index)=><div key={item.id}><input placeholder="コース名" value={item.name} onChange={e=>setCourses(old=>old.map((row,i)=>i===index?{...row,name:e.target.value}:row))}/><input aria-label="授業回数" type="number" min="1" value={item.lessons} onChange={e=>setCourses(old=>old.map((row,i)=>i===index?{...row,lessons:e.target.value}:row))}/><input aria-label="料金" type="number" min="0" value={item.price} onChange={e=>setCourses(old=>old.map((row,i)=>i===index?{...row,price:e.target.value}:row))}/><button onClick={()=>setCourses(old=>old.filter((_,i)=>i!==index))}>削除</button></div>)}<button onClick={()=>setCourses(old=>[...old,blankCourse()])}>＋コース</button></div>}
      <button className="primary" onClick={()=>post({action:'configureProgram',programId,enabled,deadline,mode,unitPrice,courses})}>申込設定を保存</button>
    </div></details>
    <details open><summary>申込・不可時間</summary><div className="application-table">{applications.map(item=>{const mine=assignments.filter(row=>row.uid===item.studentKey.replace('user_',''));return <article key={item.id}><strong>{name(item.studentKey)}</strong><span>{item.lessons}回／{Number(item.total||0).toLocaleString()}円</span><b>{statusLabel[item.status]||item.status}</b><small>不可時間 {(availability.find(row=>row.studentKey===item.studentKey)?.entries||[]).length}件</small><em>{sessions.filter(row=>row.studentKey===item.studentKey).length} / {item.lessons}回配置済み</em><small>講習課題 {mine.filter(row=>row.status==='checked').length} / {mine.length}件確認済み</small></article>})}</div></details>
    <details open><summary>授業を配置</summary><div className="session-form"><select value={session.studentKey} onChange={e=>setSession({...session,studentKey:e.target.value})}><option value="">申込生徒を選択</option>{applications.filter(item=>item.status!=='cancelled').map(item=><option key={item.studentKey} value={item.studentKey}>{name(item.studentKey)}</option>)}</select><input type="date" value={session.date} onChange={e=>setSession({...session,date:e.target.value})}/><input type="time" value={session.startTime} onChange={e=>setSession({...session,startTime:e.target.value})}/><input type="time" value={session.endTime} onChange={e=>setSession({...session,endTime:e.target.value})}/><input placeholder="教科" value={session.subject} onChange={e=>setSession({...session,subject:e.target.value})}/><button className="primary" onClick={()=>post({action:'saveSession',programId,...session})}>配置</button></div><div className="session-list">{sessions.map(item=><article key={item.id}><time>{item.date} {item.startTime}〜{item.endTime}</time><strong>{name(item.studentKey)}</strong><span>{item.subject}</span><b>同時間 {capacity[`${item.date}_${item.startTime}`]}人</b><button onClick={()=>remove('session',item.id)}>削除</button></article>)}</div></details>
  </section>;
}
